// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xdemosaic_root.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XDemosaic_root_CfgInitialize(XDemosaic_root *InstancePtr, XDemosaic_root_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Bus_axi4ls_BaseAddress = ConfigPtr->Bus_axi4ls_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XDemosaic_root_Start(XDemosaic_root *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDemosaic_root_ReadReg(InstancePtr->Bus_axi4ls_BaseAddress, XDEMOSAIC_ROOT_BUS_AXI4LS_ADDR_AP_CTRL) & 0x80;
    XDemosaic_root_WriteReg(InstancePtr->Bus_axi4ls_BaseAddress, XDEMOSAIC_ROOT_BUS_AXI4LS_ADDR_AP_CTRL, Data | 0x01);
}

u32 XDemosaic_root_IsDone(XDemosaic_root *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDemosaic_root_ReadReg(InstancePtr->Bus_axi4ls_BaseAddress, XDEMOSAIC_ROOT_BUS_AXI4LS_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XDemosaic_root_IsIdle(XDemosaic_root *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDemosaic_root_ReadReg(InstancePtr->Bus_axi4ls_BaseAddress, XDEMOSAIC_ROOT_BUS_AXI4LS_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XDemosaic_root_IsReady(XDemosaic_root *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDemosaic_root_ReadReg(InstancePtr->Bus_axi4ls_BaseAddress, XDEMOSAIC_ROOT_BUS_AXI4LS_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XDemosaic_root_EnableAutoRestart(XDemosaic_root *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDemosaic_root_WriteReg(InstancePtr->Bus_axi4ls_BaseAddress, XDEMOSAIC_ROOT_BUS_AXI4LS_ADDR_AP_CTRL, 0x80);
}

void XDemosaic_root_DisableAutoRestart(XDemosaic_root *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDemosaic_root_WriteReg(InstancePtr->Bus_axi4ls_BaseAddress, XDEMOSAIC_ROOT_BUS_AXI4LS_ADDR_AP_CTRL, 0);
}

u32 XDemosaic_root_Get_return(XDemosaic_root *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDemosaic_root_ReadReg(InstancePtr->Bus_axi4ls_BaseAddress, XDEMOSAIC_ROOT_BUS_AXI4LS_ADDR_AP_RETURN);
    return Data;
}
void XDemosaic_root_InterruptGlobalEnable(XDemosaic_root *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDemosaic_root_WriteReg(InstancePtr->Bus_axi4ls_BaseAddress, XDEMOSAIC_ROOT_BUS_AXI4LS_ADDR_GIE, 1);
}

void XDemosaic_root_InterruptGlobalDisable(XDemosaic_root *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDemosaic_root_WriteReg(InstancePtr->Bus_axi4ls_BaseAddress, XDEMOSAIC_ROOT_BUS_AXI4LS_ADDR_GIE, 0);
}

void XDemosaic_root_InterruptEnable(XDemosaic_root *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XDemosaic_root_ReadReg(InstancePtr->Bus_axi4ls_BaseAddress, XDEMOSAIC_ROOT_BUS_AXI4LS_ADDR_IER);
    XDemosaic_root_WriteReg(InstancePtr->Bus_axi4ls_BaseAddress, XDEMOSAIC_ROOT_BUS_AXI4LS_ADDR_IER, Register | Mask);
}

void XDemosaic_root_InterruptDisable(XDemosaic_root *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XDemosaic_root_ReadReg(InstancePtr->Bus_axi4ls_BaseAddress, XDEMOSAIC_ROOT_BUS_AXI4LS_ADDR_IER);
    XDemosaic_root_WriteReg(InstancePtr->Bus_axi4ls_BaseAddress, XDEMOSAIC_ROOT_BUS_AXI4LS_ADDR_IER, Register & (~Mask));
}

void XDemosaic_root_InterruptClear(XDemosaic_root *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDemosaic_root_WriteReg(InstancePtr->Bus_axi4ls_BaseAddress, XDEMOSAIC_ROOT_BUS_AXI4LS_ADDR_ISR, Mask);
}

u32 XDemosaic_root_InterruptGetEnabled(XDemosaic_root *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XDemosaic_root_ReadReg(InstancePtr->Bus_axi4ls_BaseAddress, XDEMOSAIC_ROOT_BUS_AXI4LS_ADDR_IER);
}

u32 XDemosaic_root_InterruptGetStatus(XDemosaic_root *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XDemosaic_root_ReadReg(InstancePtr->Bus_axi4ls_BaseAddress, XDEMOSAIC_ROOT_BUS_AXI4LS_ADDR_ISR);
}

