// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xdemosaic_root.h"

extern XDemosaic_root_Config XDemosaic_root_ConfigTable[];

XDemosaic_root_Config *XDemosaic_root_LookupConfig(u16 DeviceId) {
	XDemosaic_root_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XDEMOSAIC_ROOT_NUM_INSTANCES; Index++) {
		if (XDemosaic_root_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XDemosaic_root_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XDemosaic_root_Initialize(XDemosaic_root *InstancePtr, u16 DeviceId) {
	XDemosaic_root_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XDemosaic_root_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XDemosaic_root_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

