-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.2.2
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ouser is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_iuser_V_bv_V_dout : IN STD_LOGIC_VECTOR (0 downto 0);
    p_iuser_V_bv_V_empty_n : IN STD_LOGIC;
    p_iuser_V_bv_V_read : OUT STD_LOGIC;
    p_ouser_V_bv_V_din : OUT STD_LOGIC_VECTOR (0 downto 0);
    p_ouser_V_bv_V_full_n : IN STD_LOGIC;
    p_ouser_V_bv_V_write : OUT STD_LOGIC );
end;


architecture behav of ouser is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv19_0 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000000000";
    constant ap_const_lv38_0 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000000000000000000";
    constant ap_const_lv19_4B000 : STD_LOGIC_VECTOR (18 downto 0) := "1001011000000000000";
    constant ap_const_lv19_1 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000000001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv10_140 : STD_LOGIC_VECTOR (9 downto 0) := "0101000000";
    constant ap_const_lv38_CCCCD : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000011001100110011001101";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv32_1D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011101";
    constant ap_const_lv32_25 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100101";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv19_280 : STD_LOGIC_VECTOR (18 downto 0) := "0000000001010000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal p_iuser_V_bv_V_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal p_480_reg_305 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_ouser_V_bv_V_blk_n : STD_LOGIC;
    signal p_497_reg_309 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_s0_v_reg_107 : STD_LOGIC_VECTOR (18 downto 0);
    signal phi_mul_reg_118 : STD_LOGIC_VECTOR (37 downto 0);
    signal p_469_reg_129 : STD_LOGIC_VECTOR (18 downto 0);
    signal exitcond_fu_140_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state2_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal p_s0_v87_fu_146_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal p_480_fu_168_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_497_fu_174_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal next_mul_fu_180_p2 : STD_LOGIC_VECTOR (37 downto 0);
    signal p_520_2_fu_270_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_520_2_reg_318 : STD_LOGIC_VECTOR (0 downto 0);
    signal idx_urem_fu_288_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state2 : STD_LOGIC;
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal p_479_fu_156_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_2_fu_160_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_3_fu_164_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_4_fu_192_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_shl_fu_206_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal p_shl_cast_fu_214_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal p_neg_fu_218_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal p_shl1_fu_228_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_neg_cast_fu_224_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal p_shl1_cast_fu_236_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal tmp_5_fu_240_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal p_s0_v_cast_fu_152_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal p_512_fu_246_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal tmp_6_fu_252_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_510_cast_fu_202_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_4_cast_fu_260_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_509_fu_186_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_520_fu_264_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal next_urem_fu_276_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal tmp_7_fu_282_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state2);
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                elsif ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    p_469_reg_129_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (exitcond_fu_140_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                p_469_reg_129 <= idx_urem_fu_288_p3;
            elsif ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                p_469_reg_129 <= ap_const_lv19_0;
            end if; 
        end if;
    end process;

    p_s0_v_reg_107_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (exitcond_fu_140_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                p_s0_v_reg_107 <= p_s0_v87_fu_146_p2;
            elsif ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                p_s0_v_reg_107 <= ap_const_lv19_0;
            end if; 
        end if;
    end process;

    phi_mul_reg_118_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (exitcond_fu_140_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                phi_mul_reg_118 <= next_mul_fu_180_p2;
            elsif ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                phi_mul_reg_118 <= ap_const_lv38_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (exitcond_fu_140_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                p_480_reg_305 <= p_480_fu_168_p2;
                p_497_reg_309 <= p_497_fu_174_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (exitcond_fu_140_p2 = ap_const_lv1_0) and (p_497_fu_174_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                p_520_2_reg_318 <= p_520_2_fu_270_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, exitcond_fu_140_p2, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if (not(((exitcond_fu_140_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif (((exitcond_fu_140_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(1);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state4 <= ap_CS_fsm(2);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(p_iuser_V_bv_V_empty_n, p_ouser_V_bv_V_full_n, ap_enable_reg_pp0_iter1, p_480_reg_305, p_497_reg_309)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((p_497_reg_309 = ap_const_lv1_1) and (p_ouser_V_bv_V_full_n = ap_const_logic_0)) or ((p_480_reg_305 = ap_const_lv1_1) and (p_iuser_V_bv_V_empty_n = ap_const_logic_0))));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(p_iuser_V_bv_V_empty_n, p_ouser_V_bv_V_full_n, ap_enable_reg_pp0_iter1, p_480_reg_305, p_497_reg_309)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((p_497_reg_309 = ap_const_lv1_1) and (p_ouser_V_bv_V_full_n = ap_const_logic_0)) or ((p_480_reg_305 = ap_const_lv1_1) and (p_iuser_V_bv_V_empty_n = ap_const_logic_0))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(p_iuser_V_bv_V_empty_n, p_ouser_V_bv_V_full_n, ap_enable_reg_pp0_iter1, p_480_reg_305, p_497_reg_309)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((p_497_reg_309 = ap_const_lv1_1) and (p_ouser_V_bv_V_full_n = ap_const_logic_0)) or ((p_480_reg_305 = ap_const_lv1_1) and (p_iuser_V_bv_V_empty_n = ap_const_logic_0))));
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;

        ap_block_state2_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state3_pp0_stage0_iter1_assign_proc : process(p_iuser_V_bv_V_empty_n, p_ouser_V_bv_V_full_n, p_480_reg_305, p_497_reg_309)
    begin
                ap_block_state3_pp0_stage0_iter1 <= (((p_497_reg_309 = ap_const_lv1_1) and (p_ouser_V_bv_V_full_n = ap_const_logic_0)) or ((p_480_reg_305 = ap_const_lv1_1) and (p_iuser_V_bv_V_empty_n = ap_const_logic_0)));
    end process;


    ap_condition_pp0_exit_iter0_state2_assign_proc : process(exitcond_fu_140_p2)
    begin
        if ((exitcond_fu_140_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    exitcond_fu_140_p2 <= "1" when (p_s0_v_reg_107 = ap_const_lv19_4B000) else "0";
    idx_urem_fu_288_p3 <= 
        next_urem_fu_276_p2 when (tmp_7_fu_282_p2(0) = '1') else 
        ap_const_lv19_0;
    next_mul_fu_180_p2 <= std_logic_vector(unsigned(phi_mul_reg_118) + unsigned(ap_const_lv38_CCCCD));
    next_urem_fu_276_p2 <= std_logic_vector(unsigned(p_469_reg_129) + unsigned(ap_const_lv19_1));
    p_479_fu_156_p1 <= p_469_reg_129(2 - 1 downto 0);
    p_480_fu_168_p2 <= "1" when (p_479_fu_156_p1 = ap_const_lv2_0) else "0";
    p_497_fu_174_p2 <= "1" when (unsigned(tmp_2_fu_160_p1) < unsigned(ap_const_lv10_140)) else "0";
    p_4_cast_fu_260_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_6_fu_252_p3),10));
    p_509_fu_186_p2 <= "1" when (tmp_3_fu_164_p1 = ap_const_lv11_0) else "0";
    p_510_cast_fu_202_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_4_fu_192_p4),10));
    p_512_fu_246_p2 <= std_logic_vector(unsigned(tmp_5_fu_240_p2) + unsigned(p_s0_v_cast_fu_152_p1));
    p_520_2_fu_270_p2 <= (p_520_fu_264_p2 and p_509_fu_186_p2);
    p_520_fu_264_p2 <= "1" when (p_510_cast_fu_202_p1 = p_4_cast_fu_260_p1) else "0";

    p_iuser_V_bv_V_blk_n_assign_proc : process(p_iuser_V_bv_V_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, p_480_reg_305)
    begin
        if (((p_480_reg_305 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_iuser_V_bv_V_blk_n <= p_iuser_V_bv_V_empty_n;
        else 
            p_iuser_V_bv_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    p_iuser_V_bv_V_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, p_480_reg_305, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (p_480_reg_305 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_iuser_V_bv_V_read <= ap_const_logic_1;
        else 
            p_iuser_V_bv_V_read <= ap_const_logic_0;
        end if; 
    end process;

        p_neg_cast_fu_224_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_neg_fu_218_p2),20));

    p_neg_fu_218_p2 <= std_logic_vector(unsigned(ap_const_lv19_0) - unsigned(p_shl_cast_fu_214_p1));

    p_ouser_V_bv_V_blk_n_assign_proc : process(p_ouser_V_bv_V_full_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, p_497_reg_309)
    begin
        if (((p_497_reg_309 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ouser_V_bv_V_blk_n <= p_ouser_V_bv_V_full_n;
        else 
            p_ouser_V_bv_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    p_ouser_V_bv_V_din <= p_520_2_reg_318;

    p_ouser_V_bv_V_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, p_497_reg_309, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (p_497_reg_309 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ouser_V_bv_V_write <= ap_const_logic_1;
        else 
            p_ouser_V_bv_V_write <= ap_const_logic_0;
        end if; 
    end process;

    p_s0_v87_fu_146_p2 <= std_logic_vector(unsigned(p_s0_v_reg_107) + unsigned(ap_const_lv19_1));
    p_s0_v_cast_fu_152_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_s0_v_reg_107),20));
    p_shl1_cast_fu_236_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl1_fu_228_p3),20));
    p_shl1_fu_228_p3 <= (tmp_4_fu_192_p4 & ap_const_lv7_0);
    p_shl_cast_fu_214_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl_fu_206_p3),19));
    p_shl_fu_206_p3 <= (tmp_4_fu_192_p4 & ap_const_lv9_0);
    tmp_2_fu_160_p1 <= p_469_reg_129(10 - 1 downto 0);
    tmp_3_fu_164_p1 <= p_469_reg_129(11 - 1 downto 0);
    tmp_4_fu_192_p4 <= phi_mul_reg_118(37 downto 29);
    tmp_5_fu_240_p2 <= std_logic_vector(signed(p_neg_cast_fu_224_p1) - signed(p_shl1_cast_fu_236_p1));
    tmp_6_fu_252_p3 <= p_512_fu_246_p2(19 downto 19);
    tmp_7_fu_282_p2 <= "1" when (unsigned(next_urem_fu_276_p2) < unsigned(ap_const_lv19_280)) else "0";
end behav;
