// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module odata (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        p_idata_V_bv_V_dout,
        p_idata_V_bv_V_empty_n,
        p_idata_V_bv_V_read,
        p_odata_V_bv_V_din,
        p_odata_V_bv_V_full_n,
        p_odata_V_bv_V_write
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_pp0_stage0 = 5'd2;
parameter    ap_ST_fsm_state4 = 5'd4;
parameter    ap_ST_fsm_pp1_stage0 = 5'd8;
parameter    ap_ST_fsm_state12 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [39:0] p_idata_V_bv_V_dout;
input   p_idata_V_bv_V_empty_n;
output   p_idata_V_bv_V_read;
output  [23:0] p_odata_V_bv_V_din;
input   p_odata_V_bv_V_full_n;
output   p_odata_V_bv_V_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg p_idata_V_bv_V_read;
reg p_odata_V_bv_V_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    p_idata_V_bv_V_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] exitcond1_reg_2438;
wire    ap_CS_fsm_pp1_stage0;
reg    ap_enable_reg_pp1_iter1;
wire    ap_block_pp1_stage0;
reg   [0:0] p_15_reg_2604;
reg   [0:0] p_39_reg_2613;
reg    p_odata_V_bv_V_blk_n;
reg    ap_enable_reg_pp1_iter6;
reg   [0:0] exitcond_reg_2578;
reg   [0:0] exitcond_reg_2578_pp1_iter5_reg;
reg   [7:0] p_idata_buffer1_it_s_reg_359;
reg   [18:0] p_s0_v_reg_371;
reg   [37:0] phi_mul_reg_382;
reg   [37:0] phi_mul1_reg_393;
reg   [18:0] p_4_reg_404;
wire   [0:0] exitcond1_fu_424_p2;
wire    ap_block_state2_pp0_stage0_iter0;
reg    ap_block_state3_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
wire   [7:0] p_idata_buffer1_1_1_fu_430_p2;
reg   [7:0] p_idata_buffer1_1_1_reg_2442;
reg    ap_enable_reg_pp0_iter0;
reg   [39:0] p_idata_window_v0_3_reg_2457;
reg   [39:0] p_idata_window_v0_4_reg_2462;
reg   [39:0] p_idata_window_v0_5_reg_2467;
reg   [39:0] p_idata_window_0_v_2_reg_2472;
reg   [39:0] p_idata_window_1_v_2_reg_2477;
reg   [39:0] p_idata_window_2_v_2_reg_2482;
wire   [0:0] exitcond_fu_568_p2;
wire    ap_block_state5_pp1_stage0_iter0;
reg    ap_predicate_op157_read_state6;
reg    ap_block_state6_pp1_stage0_iter1;
wire    ap_block_state7_pp1_stage0_iter2;
wire    ap_block_state8_pp1_stage0_iter3;
wire    ap_block_state9_pp1_stage0_iter4;
wire    ap_block_state10_pp1_stage0_iter5;
reg    ap_block_state11_pp1_stage0_iter6;
reg    ap_block_pp1_stage0_11001;
reg   [0:0] exitcond_reg_2578_pp1_iter1_reg;
reg   [0:0] exitcond_reg_2578_pp1_iter2_reg;
reg   [0:0] exitcond_reg_2578_pp1_iter3_reg;
reg   [0:0] exitcond_reg_2578_pp1_iter4_reg;
wire   [18:0] p_s0_v55_fu_574_p2;
reg    ap_enable_reg_pp1_iter0;
wire   [0:0] p_53_fu_584_p1;
reg   [0:0] p_53_reg_2587;
reg   [0:0] p_53_reg_2587_pp1_iter1_reg;
reg   [0:0] p_53_reg_2587_pp1_iter2_reg;
reg   [0:0] p_53_reg_2587_pp1_iter3_reg;
reg   [0:0] p_53_reg_2587_pp1_iter4_reg;
wire   [1:0] p_14_fu_588_p1;
reg   [1:0] p_14_reg_2595;
reg   [1:0] p_14_reg_2595_pp1_iter1_reg;
reg   [1:0] p_14_reg_2595_pp1_iter2_reg;
wire   [0:0] p_15_fu_600_p2;
reg   [0:0] p_15_reg_2604_pp1_iter1_reg;
reg   [0:0] p_15_reg_2604_pp1_iter2_reg;
reg   [0:0] p_15_reg_2604_pp1_iter3_reg;
wire   [37:0] next_mul1_fu_606_p2;
wire   [0:0] p_39_fu_750_p2;
wire   [18:0] idx_urem_fu_768_p3;
wire   [37:0] next_mul_fu_776_p2;
wire   [0:0] p_64_fu_854_p2;
reg   [0:0] p_64_reg_2627;
reg   [0:0] p_64_reg_2627_pp1_iter1_reg;
reg   [0:0] p_64_reg_2627_pp1_iter2_reg;
reg   [0:0] p_64_reg_2627_pp1_iter3_reg;
reg   [0:0] p_64_reg_2627_pp1_iter4_reg;
wire   [0:0] p_72_fu_860_p2;
reg   [0:0] p_72_reg_2635;
reg   [0:0] p_72_reg_2635_pp1_iter1_reg;
reg   [0:0] p_72_reg_2635_pp1_iter2_reg;
reg   [0:0] p_72_reg_2635_pp1_iter3_reg;
reg   [0:0] p_72_reg_2635_pp1_iter4_reg;
wire   [0:0] p_81_fu_866_p2;
reg   [0:0] p_81_reg_2642;
reg   [0:0] p_81_reg_2642_pp1_iter1_reg;
reg   [0:0] p_81_reg_2642_pp1_iter2_reg;
reg   [0:0] p_81_reg_2642_pp1_iter3_reg;
wire   [0:0] p_88_fu_872_p2;
reg   [0:0] p_88_reg_2647;
reg   [0:0] p_88_reg_2647_pp1_iter1_reg;
reg   [0:0] p_88_reg_2647_pp1_iter2_reg;
reg   [0:0] p_88_reg_2647_pp1_iter3_reg;
reg   [0:0] p_88_reg_2647_pp1_iter4_reg;
wire   [0:0] p_92_fu_878_p2;
reg   [0:0] p_92_reg_2654;
reg   [0:0] p_92_reg_2654_pp1_iter1_reg;
reg   [0:0] p_92_reg_2654_pp1_iter2_reg;
reg   [0:0] p_92_reg_2654_pp1_iter3_reg;
reg   [0:0] p_92_reg_2654_pp1_iter4_reg;
wire   [0:0] p_101_fu_884_p2;
reg   [0:0] p_101_reg_2659;
reg   [0:0] p_101_reg_2659_pp1_iter1_reg;
reg   [0:0] p_101_reg_2659_pp1_iter2_reg;
reg   [0:0] p_101_reg_2659_pp1_iter3_reg;
reg   [0:0] p_101_reg_2659_pp1_iter4_reg;
wire   [0:0] p_106_fu_890_p2;
reg   [0:0] p_106_reg_2665;
reg   [0:0] p_106_reg_2665_pp1_iter1_reg;
reg   [0:0] p_106_reg_2665_pp1_iter2_reg;
wire   [0:0] tmp_26_fu_1048_p3;
reg   [0:0] tmp_26_reg_2681;
reg   [0:0] tmp_26_reg_2681_pp1_iter4_reg;
wire   [4:0] Lo_assign_fu_1061_p4;
reg   [4:0] Lo_assign_reg_2687;
reg   [4:0] Lo_assign_reg_2687_pp1_iter4_reg;
wire   [5:0] Hi_assign_fu_1079_p2;
reg   [5:0] Hi_assign_reg_2693;
reg   [5:0] Hi_assign_reg_2693_pp1_iter4_reg;
wire   [0:0] tmp_27_fu_1089_p2;
reg   [0:0] tmp_27_reg_2701;
wire   [0:0] tmp_53_fu_1106_p3;
reg   [0:0] tmp_53_reg_2708;
reg   [0:0] tmp_53_reg_2708_pp1_iter4_reg;
wire   [4:0] Lo_assign_1_fu_1114_p4;
reg   [4:0] Lo_assign_1_reg_2714;
wire   [5:0] Hi_assign_1_fu_1132_p2;
reg   [5:0] Hi_assign_1_reg_2720;
reg   [5:0] Hi_assign_1_reg_2720_pp1_iter4_reg;
wire   [0:0] tmp_54_fu_1142_p2;
reg   [0:0] tmp_54_reg_2728;
wire   [4:0] Lo_assign_2_fu_1148_p4;
reg   [4:0] Lo_assign_2_reg_2735;
reg   [4:0] Lo_assign_2_reg_2735_pp1_iter4_reg;
wire   [5:0] Hi_assign_2_fu_1164_p2;
reg   [5:0] Hi_assign_2_reg_2741;
reg   [5:0] Hi_assign_2_reg_2741_pp1_iter4_reg;
wire   [0:0] tmp_70_fu_1174_p2;
reg   [0:0] tmp_70_reg_2749;
reg   [0:0] tmp_70_reg_2749_pp1_iter4_reg;
wire   [5:0] tmp_95_fu_1242_p2;
reg   [5:0] tmp_95_reg_2756;
reg   [5:0] tmp_95_reg_2756_pp1_iter4_reg;
wire   [39:0] tmp_98_fu_1252_p2;
reg   [39:0] tmp_98_reg_2761;
reg   [39:0] tmp_98_reg_2761_pp1_iter4_reg;
wire   [0:0] tmp_102_fu_1258_p2;
reg   [0:0] tmp_102_reg_2766;
wire   [0:0] tmp_117_fu_1264_p2;
reg   [0:0] tmp_117_reg_2773;
reg   [0:0] tmp_117_reg_2773_pp1_iter4_reg;
wire   [0:0] tmp_133_fu_1270_p2;
reg   [0:0] tmp_133_reg_2780;
reg   [0:0] tmp_133_reg_2780_pp1_iter4_reg;
wire   [10:0] tmp2_fu_1520_p2;
reg   [10:0] tmp2_reg_2787;
reg   [10:0] tmp2_reg_2787_pp1_iter4_reg;
wire   [5:0] tmp_134_fu_1846_p1;
reg   [5:0] tmp_134_reg_2792;
wire   [5:0] tmp_137_fu_1849_p2;
reg   [5:0] tmp_137_reg_2799;
wire   [10:0] p_115_fu_1855_p2;
reg   [10:0] p_115_reg_2804;
reg   [7:0] tmp_14_reg_2809;
reg   [7:0] tmp_19_reg_2816;
wire   [7:0] p_126_fu_2285_p3;
reg   [7:0] p_126_reg_2822;
wire   [7:0] p_143_fu_2347_p3;
reg   [7:0] p_143_reg_2827;
wire   [7:0] p_160_fu_2368_p3;
reg   [7:0] p_160_reg_2832;
reg    ap_block_state1;
reg    ap_block_pp0_stage0_subdone;
wire    ap_CS_fsm_state4;
reg    ap_block_pp1_stage0_subdone;
reg    ap_condition_pp1_exit_iter0_state5;
reg    ap_enable_reg_pp1_iter2;
reg    ap_enable_reg_pp1_iter3;
reg    ap_enable_reg_pp1_iter4;
reg    ap_enable_reg_pp1_iter5;
reg   [7:0] p_idata_buffer1_0_s_address0;
reg    p_idata_buffer1_0_s_ce0;
wire   [39:0] p_idata_buffer1_0_s_q0;
reg   [7:0] p_idata_buffer1_0_s_address1;
reg    p_idata_buffer1_0_s_ce1;
reg    p_idata_buffer1_0_s_we1;
reg   [39:0] p_idata_buffer1_0_s_d1;
reg   [7:0] p_idata_buffer1_1_s_address0;
reg    p_idata_buffer1_1_s_ce0;
wire   [39:0] p_idata_buffer1_1_s_q0;
reg   [7:0] p_idata_buffer1_1_s_address1;
reg    p_idata_buffer1_1_s_ce1;
reg    p_idata_buffer1_1_s_we1;
reg   [39:0] p_idata_buffer1_1_s_d1;
reg   [7:0] ap_phi_mux_p_idata_buffer1_it_s_phi_fu_363_p4;
wire   [63:0] tmp_5_fu_442_p1;
wire   [63:0] tmp_6_fu_498_p1;
wire   [63:0] tmp_s_fu_927_p1;
wire   [63:0] tmp_2_fu_932_p1;
wire   [63:0] tmp_7_fu_993_p1;
wire   [63:0] tmp_10_fu_998_p1;
reg    ap_block_pp1_stage0_01001;
reg   [39:0] p_idata_window_v0_2_fu_180;
reg   [39:0] p_idata_window_v0_1_fu_184;
reg   [39:0] p_idata_window_v0_s_fu_188;
reg   [39:0] p_idata_window_0_v_fu_192;
reg   [39:0] p_idata_window_1_v_fu_196;
reg   [39:0] p_idata_window_2_v_fu_200;
reg   [39:0] p_idata_window_0_v_1_fu_204;
reg   [39:0] p_idata_window_1_v_1_fu_208;
reg   [39:0] p_idata_window_2_v_1_fu_212;
reg   [39:0] p_idata_window_2_v_5_fu_224;
reg   [39:0] p_idata_window_0_v_5_fu_228;
reg   [39:0] p_idata_window_0_v_6_fu_232;
reg   [39:0] p_idata_window_0_v_7_fu_236;
reg   [39:0] p_idata_window_1_v_5_fu_240;
reg   [39:0] p_idata_window_1_v_6_fu_244;
reg   [39:0] p_idata_window_1_v_7_fu_248;
reg   [39:0] p_idata_window_2_v_6_fu_252;
reg   [39:0] p_idata_window_2_v_7_fu_256;
reg   [39:0] p_idata_window_2_v_8_fu_260;
reg   [31:0] p_idata_buffer1_it_2_fu_264;
wire   [31:0] p_idata_buffer1_0_6_fu_1009_p1;
reg   [31:0] p_idata_buffer1_it_1_fu_268;
wire   [31:0] p_idata_buffer1_1_7_fu_943_p1;
wire   [7:0] tmp_2_cast_fu_436_p2;
wire   [7:0] tmp_4_fu_612_p4;
wire   [8:0] tmp_20_fu_626_p4;
wire   [17:0] p_shl2_fu_640_p3;
wire   [18:0] p_shl2_cast_fu_648_p1;
wire   [18:0] p_neg1_fu_652_p2;
wire   [15:0] p_shl3_fu_662_p3;
wire  signed [19:0] p_neg1_cast_fu_658_p1;
wire   [19:0] p_shl3_cast_fu_670_p1;
wire   [19:0] p_s0_v_cast_fu_580_p1;
wire   [19:0] tmp_9_fu_674_p2;
wire   [19:0] p_29_fu_680_p2;
wire   [0:0] tmp_21_fu_686_p3;
wire   [9:0] p_30_cast_fu_694_p3;
wire   [9:0] p_27_cast1_fu_636_p1;
wire   [9:0] p_36_fu_702_p2;
wire   [16:0] p_shl_fu_708_p3;
wire   [16:0] p_neg_fu_716_p2;
wire   [14:0] p_shl4_fu_726_p3;
wire  signed [17:0] p_neg_cast_fu_722_p1;
wire  signed [17:0] p_shl4_cast_fu_734_p1;
wire   [17:0] tmp_1_fu_738_p2;
wire   [17:0] p_26_cast_fu_622_p1;
wire   [17:0] p_38_fu_744_p2;
wire   [18:0] next_urem_fu_756_p2;
wire   [0:0] tmp_24_fu_762_p2;
wire   [8:0] tmp_11_fu_790_p4;
wire   [17:0] p_shl5_fu_800_p3;
wire   [18:0] p_shl5_cast_fu_808_p1;
wire   [18:0] p_neg2_fu_812_p2;
wire   [15:0] p_shl6_fu_822_p3;
wire  signed [19:0] p_neg2_cast_fu_818_p1;
wire   [19:0] p_shl6_cast_fu_830_p1;
wire   [19:0] tmp_12_fu_834_p2;
wire   [19:0] p_57_fu_840_p2;
wire   [0:0] tmp_25_fu_846_p3;
wire   [0:0] tmp_fu_782_p3;
wire   [10:0] tmp_18_fu_596_p1;
wire   [9:0] tmp_16_fu_592_p1;
wire   [7:0] tmp_22_fu_917_p1;
wire   [7:0] tmp_21_cast_fu_921_p2;
wire   [7:0] p_idata_buffer1_1_6_fu_937_p2;
wire   [7:0] tmp_23_fu_983_p1;
wire   [7:0] tmp_27_cast_fu_987_p2;
wire   [7:0] p_idata_buffer1_0_5_fu_1003_p2;
wire   [2:0] p_14_cast_fu_967_p1;
wire   [2:0] p_74_fu_1042_p2;
wire   [1:0] p_76_fu_1056_p2;
wire   [5:0] Lo_assign_cast1_fu_1071_p1;
wire   [31:0] Lo_assign_cast_fu_1075_p1;
wire   [31:0] Hi_assign_cast_fu_1085_p1;
wire   [2:0] p_82_fu_1095_p2;
wire   [1:0] p_84_fu_1101_p2;
wire   [5:0] Lo_assign_1_cast1_fu_1124_p1;
wire   [31:0] Lo_assign_1_cast_fu_1128_p1;
wire   [31:0] Hi_assign_1_cast_fu_1138_p1;
wire   [5:0] Lo_assign_2_cast1_fu_1156_p1;
wire   [31:0] Lo_assign_2_cast_fu_1160_p1;
wire   [31:0] Hi_assign_2_cast_fu_1170_p1;
wire   [5:0] tmp_87_fu_1186_p1;
wire   [0:0] tmp_86_fu_1180_p2;
wire   [5:0] tmp_89_fu_1200_p2;
wire   [5:0] tmp_91_fu_1212_p2;
reg   [39:0] tmp_88_fu_1190_p4;
wire   [5:0] tmp_90_fu_1206_p2;
wire   [5:0] tmp_92_fu_1218_p3;
wire   [5:0] tmp_94_fu_1234_p3;
wire   [39:0] tmp_93_fu_1226_p3;
wire   [39:0] tmp_96_fu_1248_p1;
wire   [39:0] p_Val2_7_fu_1280_p3;
wire   [5:0] tmp_150_fu_1294_p1;
wire   [0:0] tmp_149_fu_1288_p2;
wire   [5:0] tmp_152_fu_1308_p2;
wire   [5:0] tmp_154_fu_1320_p2;
reg   [39:0] tmp_151_fu_1298_p4;
wire   [5:0] tmp_153_fu_1314_p2;
wire   [5:0] tmp_155_fu_1326_p3;
wire   [5:0] tmp_157_fu_1342_p3;
wire   [5:0] tmp_158_fu_1350_p2;
wire   [39:0] tmp_156_fu_1334_p3;
wire   [39:0] tmp_159_fu_1356_p1;
wire   [39:0] tmp_160_fu_1360_p1;
wire   [39:0] tmp_161_fu_1364_p2;
wire   [39:0] tmp_162_fu_1370_p2;
wire   [39:0] p_Result_7_fu_1376_p2;
wire   [0:0] p_107_fu_1276_p2;
wire   [9:0] tmp_164_fu_1382_p1;
wire   [9:0] p_110_fu_1386_p3;
wire   [39:0] p_Val2_8_fu_1402_p3;
wire   [5:0] tmp_166_fu_1416_p1;
wire   [0:0] tmp_165_fu_1410_p2;
wire   [5:0] tmp_168_fu_1430_p2;
wire   [5:0] tmp_170_fu_1442_p2;
reg   [39:0] tmp_167_fu_1420_p4;
wire   [5:0] tmp_169_fu_1436_p2;
wire   [5:0] tmp_171_fu_1448_p3;
wire   [5:0] tmp_173_fu_1464_p3;
wire   [5:0] tmp_174_fu_1472_p2;
wire   [39:0] tmp_172_fu_1456_p3;
wire   [39:0] tmp_175_fu_1478_p1;
wire   [39:0] tmp_176_fu_1482_p1;
wire   [39:0] tmp_177_fu_1486_p2;
wire   [39:0] tmp_178_fu_1492_p2;
wire   [39:0] p_Result_8_fu_1498_p2;
wire   [0:0] p_106_2_fu_1398_p2;
wire   [9:0] tmp_180_fu_1504_p1;
wire   [9:0] p_114_fu_1508_p3;
wire   [10:0] p_114_cast_cast_fu_1516_p1;
wire   [10:0] p_110_cast_cast_fu_1394_p1;
wire   [39:0] p_Val2_s_fu_1556_p3;
wire   [5:0] tmp_28_fu_1563_p1;
wire   [5:0] tmp_33_fu_1576_p2;
wire   [5:0] tmp_40_fu_1587_p2;
reg   [39:0] tmp_29_fu_1566_p4;
wire   [5:0] tmp_34_fu_1581_p2;
wire   [5:0] tmp_41_fu_1592_p3;
wire   [5:0] tmp_43_fu_1606_p3;
wire   [5:0] tmp_44_fu_1613_p2;
wire   [39:0] tmp_42_fu_1599_p3;
wire   [39:0] tmp_47_fu_1619_p1;
wire   [39:0] tmp_48_fu_1623_p1;
wire   [39:0] tmp_49_fu_1627_p2;
wire   [39:0] tmp_50_fu_1633_p2;
wire   [39:0] p_Result_s_fu_1639_p2;
wire   [9:0] tmp_52_fu_1645_p1;
wire   [9:0] p_80_fu_1649_p3;
wire   [39:0] p_Val2_1_fu_1660_p3;
wire   [5:0] tmp_55_fu_1667_p1;
wire   [5:0] tmp_57_fu_1680_p2;
wire   [5:0] tmp_59_fu_1691_p2;
reg   [39:0] tmp_56_fu_1670_p4;
wire   [5:0] tmp_58_fu_1685_p2;
wire   [5:0] tmp_60_fu_1696_p3;
wire   [5:0] tmp_62_fu_1710_p3;
wire   [5:0] tmp_63_fu_1717_p2;
wire   [39:0] tmp_61_fu_1703_p3;
wire   [39:0] tmp_64_fu_1723_p1;
wire   [39:0] tmp_65_fu_1727_p1;
wire   [39:0] tmp_66_fu_1731_p2;
wire   [39:0] tmp_67_fu_1737_p2;
wire   [39:0] p_Result_1_fu_1743_p2;
wire   [9:0] tmp_69_fu_1749_p1;
wire   [9:0] p_87_fu_1753_p3;
wire   [5:0] tmp_103_fu_1764_p1;
wire   [5:0] tmp_105_fu_1777_p2;
wire   [5:0] tmp_107_fu_1788_p2;
reg   [39:0] tmp_104_fu_1767_p4;
wire   [5:0] tmp_106_fu_1782_p2;
wire   [5:0] tmp_108_fu_1793_p3;
wire   [5:0] tmp_110_fu_1807_p3;
wire   [5:0] tmp_111_fu_1814_p2;
wire   [39:0] tmp_109_fu_1800_p3;
wire   [39:0] tmp_112_fu_1820_p1;
wire   [39:0] tmp_113_fu_1824_p1;
wire   [39:0] tmp_114_fu_1828_p2;
wire   [39:0] tmp_115_fu_1834_p2;
wire   [10:0] p_87_cast_fu_1760_p1;
wire   [10:0] p_80_cast_fu_1656_p1;
wire   [39:0] p_Result_4_fu_1840_p2;
wire   [0:0] p_66_fu_1895_p2;
wire   [0:0] p_54_fu_1890_p2;
wire   [5:0] tmp_71_fu_1914_p1;
wire   [5:0] tmp_73_fu_1927_p2;
wire   [5:0] tmp_75_fu_1938_p2;
reg   [39:0] tmp_72_fu_1917_p4;
wire   [5:0] tmp_74_fu_1932_p2;
wire   [5:0] tmp_76_fu_1943_p3;
wire   [5:0] tmp_78_fu_1957_p3;
wire   [5:0] tmp_79_fu_1964_p2;
wire   [39:0] tmp_77_fu_1950_p3;
wire   [39:0] tmp_80_fu_1970_p1;
wire   [39:0] tmp_81_fu_1974_p1;
wire   [39:0] tmp_82_fu_1978_p2;
wire   [39:0] tmp_83_fu_1984_p2;
wire   [39:0] p_Result_2_fu_1990_p2;
wire   [9:0] tmp_85_fu_1996_p1;
wire   [9:0] p_91_fu_2000_p3;
wire   [39:0] tmp_97_fu_2011_p1;
wire   [39:0] tmp_99_fu_2014_p2;
wire   [39:0] p_Result_3_fu_2020_p2;
wire   [9:0] tmp_101_fu_2025_p1;
wire   [9:0] p_95_fu_2029_p3;
wire   [39:0] p_Val2_5_fu_2044_p3;
wire   [5:0] tmp_118_fu_2051_p1;
wire   [5:0] tmp_120_fu_2064_p2;
wire   [5:0] tmp_122_fu_2075_p2;
reg   [39:0] tmp_119_fu_2054_p4;
wire   [5:0] tmp_121_fu_2069_p2;
wire   [5:0] tmp_123_fu_2080_p3;
wire   [5:0] tmp_125_fu_2094_p3;
wire   [5:0] tmp_126_fu_2101_p2;
wire   [39:0] tmp_124_fu_2087_p3;
wire   [39:0] tmp_127_fu_2107_p1;
wire   [39:0] tmp_128_fu_2111_p1;
wire   [39:0] tmp_129_fu_2115_p2;
wire   [39:0] tmp_130_fu_2121_p2;
wire   [39:0] p_Result_5_fu_2127_p2;
wire   [0:0] p_97_fu_2040_p2;
wire   [9:0] tmp_132_fu_2133_p1;
wire   [9:0] p_100_fu_2137_p3;
wire   [39:0] p_Val2_6_fu_2153_p3;
wire   [5:0] tmp_136_fu_2170_p2;
wire   [5:0] tmp_138_fu_2174_p2;
reg   [39:0] tmp_135_fu_2160_p4;
wire   [5:0] tmp_139_fu_2178_p3;
wire   [5:0] tmp_141_fu_2192_p3;
wire   [5:0] tmp_142_fu_2197_p2;
wire   [39:0] tmp_140_fu_2185_p3;
wire   [39:0] tmp_143_fu_2203_p1;
wire   [39:0] tmp_144_fu_2207_p1;
wire   [39:0] tmp_145_fu_2211_p2;
wire   [39:0] tmp_146_fu_2217_p2;
wire   [39:0] p_Result_6_fu_2223_p2;
wire   [0:0] p_88_2_fu_2149_p2;
wire   [9:0] tmp_148_fu_2229_p1;
wire   [9:0] p_105_fu_2233_p3;
wire   [10:0] p_95_cast1_fu_2036_p1;
wire   [10:0] p_91_cast1_fu_2007_p1;
wire   [10:0] p_132_fu_2248_p2;
wire   [11:0] p_115_cast_fu_2245_p1;
wire   [11:0] tmp1_cast_fu_2254_p1;
wire   [11:0] p_117_fu_2258_p2;
wire   [0:0] p_121_fu_2264_p2;
wire   [7:0] tmp_15_fu_2268_p4;
wire   [0:0] tmp_13_fu_1900_p2;
wire   [7:0] tmp_17_fu_2278_p3;
wire   [10:0] p_100_cast_fu_2145_p1;
wire   [10:0] p_105_cast_fu_2241_p1;
wire   [10:0] p_134_fu_2293_p2;
wire   [11:0] p_134_cast_fu_2299_p1;
wire   [11:0] tmp2_cast_fu_2303_p1;
wire   [11:0] p_136_fu_2306_p2;
wire   [0:0] p_70_fu_1909_p2;
wire   [7:0] tmp_30_fu_2312_p4;
wire   [7:0] tmp_31_fu_2322_p4;
wire   [0:0] p_69_fu_1904_p2;
wire   [7:0] tmp_32_fu_2332_p3;
wire   [7:0] tmp_35_fu_2340_p3;
wire   [7:0] tmp_36_fu_2354_p3;
wire   [7:0] tmp_37_fu_2360_p3;
wire    ap_CS_fsm_state12;
reg   [4:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_idle_pp1;
wire    ap_enable_pp1;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 5'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp1_iter1 = 1'b0;
#0 ap_enable_reg_pp1_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp1_iter0 = 1'b0;
#0 ap_enable_reg_pp1_iter2 = 1'b0;
#0 ap_enable_reg_pp1_iter3 = 1'b0;
#0 ap_enable_reg_pp1_iter4 = 1'b0;
#0 ap_enable_reg_pp1_iter5 = 1'b0;
end

odata_p_idata_bufbkb #(
    .DataWidth( 40 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
p_idata_buffer1_0_s_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_idata_buffer1_0_s_address0),
    .ce0(p_idata_buffer1_0_s_ce0),
    .q0(p_idata_buffer1_0_s_q0),
    .address1(p_idata_buffer1_0_s_address1),
    .ce1(p_idata_buffer1_0_s_ce1),
    .we1(p_idata_buffer1_0_s_we1),
    .d1(p_idata_buffer1_0_s_d1)
);

odata_p_idata_bufbkb #(
    .DataWidth( 40 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
p_idata_buffer1_1_s_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_idata_buffer1_1_s_address0),
    .ce0(p_idata_buffer1_1_s_ce0),
    .q0(p_idata_buffer1_1_s_q0),
    .address1(p_idata_buffer1_1_s_address1),
    .ce1(p_idata_buffer1_1_s_ce1),
    .we1(p_idata_buffer1_1_s_we1),
    .d1(p_idata_buffer1_1_s_d1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state12)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((exitcond1_fu_424_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp1_stage0_subdone) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b1 == ap_condition_pp1_exit_iter0_state5))) begin
            ap_enable_reg_pp1_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state4)) begin
            ap_enable_reg_pp1_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp1_exit_iter0_state5)) begin
                ap_enable_reg_pp1_iter1 <= (1'b1 ^ ap_condition_pp1_exit_iter0_state5);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter2 <= ap_enable_reg_pp1_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter3 <= ap_enable_reg_pp1_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter4 <= ap_enable_reg_pp1_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter5 <= ap_enable_reg_pp1_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter6 <= ap_enable_reg_pp1_iter5;
        end else if ((1'b1 == ap_CS_fsm_state4)) begin
            ap_enable_reg_pp1_iter6 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        p_4_reg_404 <= 19'd0;
    end else if (((exitcond_fu_568_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        p_4_reg_404 <= idx_urem_fu_768_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((p_15_reg_2604_pp1_iter1_reg == 1'd1) & (ap_enable_reg_pp1_iter2 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
                p_idata_buffer1_it_1_fu_268[7 : 0] <= p_idata_buffer1_1_7_fu_943_p1[7 : 0];
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
                p_idata_buffer1_it_1_fu_268[0] <= 1'b1;
        p_idata_buffer1_it_1_fu_268[1] <= 1'b0;
        p_idata_buffer1_it_1_fu_268[2] <= 1'b0;
        p_idata_buffer1_it_1_fu_268[3] <= 1'b0;
        p_idata_buffer1_it_1_fu_268[4] <= 1'b0;
        p_idata_buffer1_it_1_fu_268[5] <= 1'b1;
        p_idata_buffer1_it_1_fu_268[6] <= 1'b0;
        p_idata_buffer1_it_1_fu_268[7] <= 1'b1;
    end
end

always @ (posedge ap_clk) begin
    if (((p_15_reg_2604_pp1_iter2_reg == 1'd1) & (ap_enable_reg_pp1_iter3 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
                p_idata_buffer1_it_2_fu_264[7 : 0] <= p_idata_buffer1_0_6_fu_1009_p1[7 : 0];
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
                p_idata_buffer1_it_2_fu_264[0] <= 1'b1;
        p_idata_buffer1_it_2_fu_264[1] <= 1'b0;
        p_idata_buffer1_it_2_fu_264[2] <= 1'b0;
        p_idata_buffer1_it_2_fu_264[3] <= 1'b0;
        p_idata_buffer1_it_2_fu_264[4] <= 1'b0;
        p_idata_buffer1_it_2_fu_264[5] <= 1'b1;
        p_idata_buffer1_it_2_fu_264[6] <= 1'b0;
        p_idata_buffer1_it_2_fu_264[7] <= 1'b1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_idata_buffer1_it_s_reg_359 <= 8'd0;
    end else if (((exitcond1_reg_2438 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_idata_buffer1_it_s_reg_359 <= p_idata_buffer1_1_1_reg_2442;
    end
end

always @ (posedge ap_clk) begin
    if (((p_15_reg_2604_pp1_iter3_reg == 1'd1) & (ap_enable_reg_pp1_iter4 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        p_idata_window_0_v_5_fu_228 <= p_idata_buffer1_0_s_q0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        p_idata_window_0_v_5_fu_228 <= p_idata_window_0_v_1_fu_204;
    end
end

always @ (posedge ap_clk) begin
    if (((p_15_reg_2604_pp1_iter3_reg == 1'd1) & (ap_enable_reg_pp1_iter4 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        p_idata_window_0_v_6_fu_232 <= p_idata_window_0_v_5_fu_228;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        p_idata_window_0_v_6_fu_232 <= p_idata_window_0_v_2_reg_2472;
    end
end

always @ (posedge ap_clk) begin
    if (((p_15_reg_2604_pp1_iter3_reg == 1'd1) & (ap_enable_reg_pp1_iter4 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        p_idata_window_0_v_7_fu_236 <= p_idata_window_0_v_6_fu_232;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        p_idata_window_0_v_7_fu_236 <= p_idata_window_v0_3_reg_2457;
    end
end

always @ (posedge ap_clk) begin
    if (((p_15_reg_2604_pp1_iter2_reg == 1'd1) & (ap_enable_reg_pp1_iter3 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        p_idata_window_1_v_5_fu_240 <= p_idata_buffer1_1_s_q0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        p_idata_window_1_v_5_fu_240 <= p_idata_window_1_v_1_fu_208;
    end
end

always @ (posedge ap_clk) begin
    if (((p_15_reg_2604_pp1_iter2_reg == 1'd1) & (ap_enable_reg_pp1_iter3 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        p_idata_window_1_v_6_fu_244 <= p_idata_window_1_v_5_fu_240;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        p_idata_window_1_v_6_fu_244 <= p_idata_window_1_v_2_reg_2477;
    end
end

always @ (posedge ap_clk) begin
    if (((p_15_reg_2604_pp1_iter2_reg == 1'd1) & (ap_enable_reg_pp1_iter3 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        p_idata_window_1_v_7_fu_248 <= p_idata_window_1_v_6_fu_244;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        p_idata_window_1_v_7_fu_248 <= p_idata_window_v0_4_reg_2462;
    end
end

always @ (posedge ap_clk) begin
    if (((p_15_reg_2604_pp1_iter1_reg == 1'd1) & (ap_enable_reg_pp1_iter2 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        p_idata_window_2_v_6_fu_252 <= p_idata_window_2_v_5_fu_224;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        p_idata_window_2_v_6_fu_252 <= p_idata_window_2_v_1_fu_212;
    end
end

always @ (posedge ap_clk) begin
    if (((p_15_reg_2604_pp1_iter1_reg == 1'd1) & (ap_enable_reg_pp1_iter2 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        p_idata_window_2_v_7_fu_256 <= p_idata_window_2_v_6_fu_252;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        p_idata_window_2_v_7_fu_256 <= p_idata_window_2_v_2_reg_2482;
    end
end

always @ (posedge ap_clk) begin
    if (((p_15_reg_2604_pp1_iter1_reg == 1'd1) & (ap_enable_reg_pp1_iter2 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        p_idata_window_2_v_8_fu_260 <= p_idata_window_2_v_7_fu_256;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        p_idata_window_2_v_8_fu_260 <= p_idata_window_v0_5_reg_2467;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        p_s0_v_reg_371 <= 19'd0;
    end else if (((exitcond_fu_568_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        p_s0_v_reg_371 <= p_s0_v55_fu_574_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        phi_mul1_reg_393 <= 38'd0;
    end else if (((exitcond_fu_568_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        phi_mul1_reg_393 <= next_mul1_fu_606_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        phi_mul_reg_382 <= 38'd0;
    end else if (((exitcond_fu_568_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        phi_mul_reg_382 <= next_mul_fu_776_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_reg_2578_pp1_iter2_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        Hi_assign_1_reg_2720[5 : 1] <= Hi_assign_1_fu_1132_p2[5 : 1];
        Hi_assign_2_reg_2741[5 : 1] <= Hi_assign_2_fu_1164_p2[5 : 1];
        Hi_assign_reg_2693[5 : 1] <= Hi_assign_fu_1079_p2[5 : 1];
        Lo_assign_1_reg_2714[4 : 1] <= Lo_assign_1_fu_1114_p4[4 : 1];
        Lo_assign_2_reg_2735[4 : 1] <= Lo_assign_2_fu_1148_p4[4 : 1];
        Lo_assign_reg_2687[4 : 1] <= Lo_assign_fu_1061_p4[4 : 1];
        tmp2_reg_2787 <= tmp2_fu_1520_p2;
        tmp_102_reg_2766 <= tmp_102_fu_1258_p2;
        tmp_117_reg_2773 <= tmp_117_fu_1264_p2;
        tmp_133_reg_2780 <= tmp_133_fu_1270_p2;
        tmp_26_reg_2681 <= p_74_fu_1042_p2[32'd2];
        tmp_53_reg_2708 <= p_82_fu_1095_p2[32'd2];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp1_stage0_11001)) begin
        Hi_assign_1_reg_2720_pp1_iter4_reg[5 : 1] <= Hi_assign_1_reg_2720[5 : 1];
        Hi_assign_2_reg_2741_pp1_iter4_reg[5 : 1] <= Hi_assign_2_reg_2741[5 : 1];
        Hi_assign_reg_2693_pp1_iter4_reg[5 : 1] <= Hi_assign_reg_2693[5 : 1];
        Lo_assign_2_reg_2735_pp1_iter4_reg[4 : 1] <= Lo_assign_2_reg_2735[4 : 1];
        Lo_assign_reg_2687_pp1_iter4_reg[4 : 1] <= Lo_assign_reg_2687[4 : 1];
        exitcond_reg_2578_pp1_iter2_reg <= exitcond_reg_2578_pp1_iter1_reg;
        exitcond_reg_2578_pp1_iter3_reg <= exitcond_reg_2578_pp1_iter2_reg;
        exitcond_reg_2578_pp1_iter4_reg <= exitcond_reg_2578_pp1_iter3_reg;
        exitcond_reg_2578_pp1_iter5_reg <= exitcond_reg_2578_pp1_iter4_reg;
        p_101_reg_2659_pp1_iter2_reg <= p_101_reg_2659_pp1_iter1_reg;
        p_101_reg_2659_pp1_iter3_reg <= p_101_reg_2659_pp1_iter2_reg;
        p_101_reg_2659_pp1_iter4_reg <= p_101_reg_2659_pp1_iter3_reg;
        p_106_reg_2665_pp1_iter2_reg <= p_106_reg_2665_pp1_iter1_reg;
        p_14_reg_2595_pp1_iter2_reg <= p_14_reg_2595_pp1_iter1_reg;
        p_15_reg_2604_pp1_iter2_reg <= p_15_reg_2604_pp1_iter1_reg;
        p_15_reg_2604_pp1_iter3_reg <= p_15_reg_2604_pp1_iter2_reg;
        p_53_reg_2587_pp1_iter2_reg <= p_53_reg_2587_pp1_iter1_reg;
        p_53_reg_2587_pp1_iter3_reg <= p_53_reg_2587_pp1_iter2_reg;
        p_53_reg_2587_pp1_iter4_reg <= p_53_reg_2587_pp1_iter3_reg;
        p_64_reg_2627_pp1_iter2_reg <= p_64_reg_2627_pp1_iter1_reg;
        p_64_reg_2627_pp1_iter3_reg <= p_64_reg_2627_pp1_iter2_reg;
        p_64_reg_2627_pp1_iter4_reg <= p_64_reg_2627_pp1_iter3_reg;
        p_72_reg_2635_pp1_iter2_reg <= p_72_reg_2635_pp1_iter1_reg;
        p_72_reg_2635_pp1_iter3_reg <= p_72_reg_2635_pp1_iter2_reg;
        p_72_reg_2635_pp1_iter4_reg <= p_72_reg_2635_pp1_iter3_reg;
        p_81_reg_2642_pp1_iter2_reg <= p_81_reg_2642_pp1_iter1_reg;
        p_81_reg_2642_pp1_iter3_reg <= p_81_reg_2642_pp1_iter2_reg;
        p_88_reg_2647_pp1_iter2_reg <= p_88_reg_2647_pp1_iter1_reg;
        p_88_reg_2647_pp1_iter3_reg <= p_88_reg_2647_pp1_iter2_reg;
        p_88_reg_2647_pp1_iter4_reg <= p_88_reg_2647_pp1_iter3_reg;
        p_92_reg_2654_pp1_iter2_reg <= p_92_reg_2654_pp1_iter1_reg;
        p_92_reg_2654_pp1_iter3_reg <= p_92_reg_2654_pp1_iter2_reg;
        p_92_reg_2654_pp1_iter4_reg <= p_92_reg_2654_pp1_iter3_reg;
        tmp2_reg_2787_pp1_iter4_reg <= tmp2_reg_2787;
        tmp_117_reg_2773_pp1_iter4_reg <= tmp_117_reg_2773;
        tmp_133_reg_2780_pp1_iter4_reg <= tmp_133_reg_2780;
        tmp_26_reg_2681_pp1_iter4_reg <= tmp_26_reg_2681;
        tmp_53_reg_2708_pp1_iter4_reg <= tmp_53_reg_2708;
        tmp_70_reg_2749_pp1_iter4_reg <= tmp_70_reg_2749;
        tmp_95_reg_2756_pp1_iter4_reg[5 : 1] <= tmp_95_reg_2756[5 : 1];
        tmp_98_reg_2761_pp1_iter4_reg <= tmp_98_reg_2761;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        exitcond1_reg_2438 <= exitcond1_fu_424_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        exitcond_reg_2578 <= exitcond_fu_568_p2;
        exitcond_reg_2578_pp1_iter1_reg <= exitcond_reg_2578;
        p_101_reg_2659_pp1_iter1_reg <= p_101_reg_2659;
        p_106_reg_2665_pp1_iter1_reg <= p_106_reg_2665;
        p_14_reg_2595_pp1_iter1_reg <= p_14_reg_2595;
        p_15_reg_2604_pp1_iter1_reg <= p_15_reg_2604;
        p_53_reg_2587_pp1_iter1_reg <= p_53_reg_2587;
        p_64_reg_2627_pp1_iter1_reg <= p_64_reg_2627;
        p_72_reg_2635_pp1_iter1_reg <= p_72_reg_2635;
        p_81_reg_2642_pp1_iter1_reg <= p_81_reg_2642;
        p_88_reg_2647_pp1_iter1_reg <= p_88_reg_2647;
        p_92_reg_2654_pp1_iter1_reg <= p_92_reg_2654;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_fu_568_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        p_101_reg_2659 <= p_101_fu_884_p2;
        p_106_reg_2665 <= p_106_fu_890_p2;
        p_14_reg_2595 <= p_14_fu_588_p1;
        p_15_reg_2604 <= p_15_fu_600_p2;
        p_53_reg_2587 <= p_53_fu_584_p1;
        p_64_reg_2627 <= p_64_fu_854_p2;
        p_72_reg_2635 <= p_72_fu_860_p2;
        p_81_reg_2642 <= p_81_fu_866_p2;
        p_88_reg_2647 <= p_88_fu_872_p2;
        p_92_reg_2654 <= p_92_fu_878_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_reg_2578_pp1_iter3_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        p_115_reg_2804 <= p_115_fu_1855_p2;
        tmp_134_reg_2792[4 : 1] <= tmp_134_fu_1846_p1[4 : 1];
        tmp_14_reg_2809 <= {{p_Result_4_fu_1840_p2[9:2]}};
        tmp_19_reg_2816 <= {{p_115_fu_1855_p2[10:3]}};
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_reg_2578_pp1_iter4_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        p_126_reg_2822 <= p_126_fu_2285_p3;
        p_143_reg_2827 <= p_143_fu_2347_p3;
        p_160_reg_2832 <= p_160_fu_2368_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((p_15_fu_600_p2 == 1'd1) & (exitcond_fu_568_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        p_39_reg_2613 <= p_39_fu_750_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_idata_buffer1_1_1_reg_2442 <= p_idata_buffer1_1_1_fu_430_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond1_reg_2438 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_idata_window_0_v_1_fu_204 <= p_idata_buffer1_0_s_q0;
        p_idata_window_1_v_1_fu_208 <= p_idata_buffer1_1_s_q0;
        p_idata_window_2_v_1_fu_212 <= p_idata_V_bv_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_idata_window_0_v_2_reg_2472 <= p_idata_window_0_v_fu_192;
        p_idata_window_0_v_fu_192 <= p_idata_window_0_v_1_fu_204;
        p_idata_window_1_v_2_reg_2477 <= p_idata_window_1_v_fu_196;
        p_idata_window_1_v_fu_196 <= p_idata_window_1_v_1_fu_208;
        p_idata_window_2_v_2_reg_2482 <= p_idata_window_2_v_fu_200;
        p_idata_window_2_v_fu_200 <= p_idata_window_2_v_1_fu_212;
        p_idata_window_v0_1_fu_184 <= p_idata_window_1_v_fu_196;
        p_idata_window_v0_2_fu_180 <= p_idata_window_0_v_fu_192;
        p_idata_window_v0_3_reg_2457 <= p_idata_window_v0_2_fu_180;
        p_idata_window_v0_4_reg_2462 <= p_idata_window_v0_1_fu_184;
        p_idata_window_v0_5_reg_2467 <= p_idata_window_v0_s_fu_188;
        p_idata_window_v0_s_fu_188 <= p_idata_window_2_v_fu_200;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (ap_predicate_op157_read_state6 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        p_idata_window_2_v_5_fu_224 <= p_idata_V_bv_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_133_reg_2780 == 1'd1) & (exitcond_reg_2578_pp1_iter3_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        tmp_137_reg_2799[5 : 1] <= tmp_137_fu_1849_p2[5 : 1];
    end
end

always @ (posedge ap_clk) begin
    if (((p_72_reg_2635_pp1_iter2_reg == 1'd0) & (exitcond_reg_2578_pp1_iter2_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        tmp_27_reg_2701 <= tmp_27_fu_1089_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((p_81_reg_2642_pp1_iter2_reg == 1'd1) & (exitcond_reg_2578_pp1_iter2_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        tmp_54_reg_2728 <= tmp_54_fu_1142_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((p_88_reg_2647_pp1_iter2_reg == 1'd0) & (exitcond_reg_2578_pp1_iter2_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        tmp_70_reg_2749 <= tmp_70_fu_1174_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((p_92_reg_2654_pp1_iter2_reg == 1'd1) & (exitcond_reg_2578_pp1_iter2_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        tmp_95_reg_2756[5 : 1] <= tmp_95_fu_1242_p2[5 : 1];
        tmp_98_reg_2761 <= tmp_98_fu_1252_p2;
    end
end

always @ (*) begin
    if ((exitcond_fu_568_p2 == 1'd1)) begin
        ap_condition_pp1_exit_iter0_state5 = 1'b1;
    end else begin
        ap_condition_pp1_exit_iter0_state5 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter6 == 1'b0) & (ap_enable_reg_pp1_iter1 == 1'b0) & (ap_enable_reg_pp1_iter5 == 1'b0) & (ap_enable_reg_pp1_iter4 == 1'b0) & (ap_enable_reg_pp1_iter3 == 1'b0) & (ap_enable_reg_pp1_iter2 == 1'b0) & (ap_enable_reg_pp1_iter0 == 1'b0))) begin
        ap_idle_pp1 = 1'b1;
    end else begin
        ap_idle_pp1 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond1_reg_2438 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_p_idata_buffer1_it_s_phi_fu_363_p4 = p_idata_buffer1_1_1_reg_2442;
    end else begin
        ap_phi_mux_p_idata_buffer1_it_s_phi_fu_363_p4 = p_idata_buffer1_it_s_reg_359;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((((p_39_reg_2613 == 1'd1) & (p_15_reg_2604 == 1'd1) & (1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)) | ((exitcond1_reg_2438 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_idata_V_bv_V_blk_n = p_idata_V_bv_V_empty_n;
    end else begin
        p_idata_V_bv_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (ap_predicate_op157_read_state6 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)) | ((exitcond1_reg_2438 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        p_idata_V_bv_V_read = 1'b1;
    end else begin
        p_idata_V_bv_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter3 == 1'b1))) begin
        p_idata_buffer1_0_s_address0 = tmp_7_fu_993_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_idata_buffer1_0_s_address0 = tmp_5_fu_442_p1;
    end else begin
        p_idata_buffer1_0_s_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter3 == 1'b1))) begin
        p_idata_buffer1_0_s_address1 = tmp_10_fu_998_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_idata_buffer1_0_s_address1 = tmp_6_fu_498_p1;
    end else begin
        p_idata_buffer1_0_s_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp1_iter3 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        p_idata_buffer1_0_s_ce0 = 1'b1;
    end else begin
        p_idata_buffer1_0_s_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp1_iter3 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        p_idata_buffer1_0_s_ce1 = 1'b1;
    end else begin
        p_idata_buffer1_0_s_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter3 == 1'b1))) begin
        p_idata_buffer1_0_s_d1 = p_idata_window_1_v_7_fu_248;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_idata_buffer1_0_s_d1 = p_idata_window_v0_1_fu_184;
    end else begin
        p_idata_buffer1_0_s_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((exitcond1_reg_2438 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((p_15_reg_2604_pp1_iter2_reg == 1'd1) & (ap_enable_reg_pp1_iter3 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        p_idata_buffer1_0_s_we1 = 1'b1;
    end else begin
        p_idata_buffer1_0_s_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        p_idata_buffer1_1_s_address0 = tmp_s_fu_927_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        p_idata_buffer1_1_s_address0 = tmp_5_fu_442_p1;
    end else begin
        p_idata_buffer1_1_s_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        p_idata_buffer1_1_s_address1 = tmp_2_fu_932_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_idata_buffer1_1_s_address1 = tmp_6_fu_498_p1;
    end else begin
        p_idata_buffer1_1_s_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp1_iter2 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        p_idata_buffer1_1_s_ce0 = 1'b1;
    end else begin
        p_idata_buffer1_1_s_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp1_iter2 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        p_idata_buffer1_1_s_ce1 = 1'b1;
    end else begin
        p_idata_buffer1_1_s_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        p_idata_buffer1_1_s_d1 = p_idata_window_2_v_8_fu_260;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_idata_buffer1_1_s_d1 = p_idata_window_v0_s_fu_188;
    end else begin
        p_idata_buffer1_1_s_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((exitcond1_reg_2438 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((p_15_reg_2604_pp1_iter1_reg == 1'd1) & (ap_enable_reg_pp1_iter2 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        p_idata_buffer1_1_s_we1 = 1'b1;
    end else begin
        p_idata_buffer1_1_s_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (exitcond_reg_2578_pp1_iter5_reg == 1'd0) & (ap_enable_reg_pp1_iter6 == 1'b1))) begin
        p_odata_V_bv_V_blk_n = p_odata_V_bv_V_full_n;
    end else begin
        p_odata_V_bv_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((exitcond_reg_2578_pp1_iter5_reg == 1'd0) & (ap_enable_reg_pp1_iter6 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        p_odata_V_bv_V_write = 1'b1;
    end else begin
        p_odata_V_bv_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_pp1_stage0;
        end
        ap_ST_fsm_pp1_stage0 : begin
            if ((~((exitcond_fu_568_p2 == 1'd1) & (ap_enable_reg_pp1_iter1 == 1'b0) & (1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter0 == 1'b1)) & ~((ap_enable_reg_pp1_iter5 == 1'b0) & (1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter6 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else if ((((ap_enable_reg_pp1_iter5 == 1'b0) & (1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter6 == 1'b1)) | ((exitcond_fu_568_p2 == 1'd1) & (ap_enable_reg_pp1_iter1 == 1'b0) & (1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter0 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Hi_assign_1_cast_fu_1138_p1 = Hi_assign_1_fu_1132_p2;

assign Hi_assign_1_fu_1132_p2 = (6'd9 + Lo_assign_1_cast1_fu_1124_p1);

assign Hi_assign_2_cast_fu_1170_p1 = Hi_assign_2_fu_1164_p2;

assign Hi_assign_2_fu_1164_p2 = (6'd9 + Lo_assign_2_cast1_fu_1156_p1);

assign Hi_assign_cast_fu_1085_p1 = Hi_assign_fu_1079_p2;

assign Hi_assign_fu_1079_p2 = (6'd9 + Lo_assign_cast1_fu_1071_p1);

assign Lo_assign_1_cast1_fu_1124_p1 = Lo_assign_1_fu_1114_p4;

assign Lo_assign_1_cast_fu_1128_p1 = Lo_assign_1_fu_1114_p4;

assign Lo_assign_1_fu_1114_p4 = {{{p_84_fu_1101_p2}, {p_84_fu_1101_p2}}, {1'd0}};

assign Lo_assign_2_cast1_fu_1156_p1 = Lo_assign_2_fu_1148_p4;

assign Lo_assign_2_cast_fu_1160_p1 = Lo_assign_2_fu_1148_p4;

assign Lo_assign_2_fu_1148_p4 = {{{p_14_reg_2595_pp1_iter2_reg}, {p_14_reg_2595_pp1_iter2_reg}}, {1'd0}};

assign Lo_assign_cast1_fu_1071_p1 = Lo_assign_fu_1061_p4;

assign Lo_assign_cast_fu_1075_p1 = Lo_assign_fu_1061_p4;

assign Lo_assign_fu_1061_p4 = {{{p_76_fu_1056_p2}, {p_76_fu_1056_p2}}, {1'd0}};

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp1_stage0 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((exitcond1_reg_2438 == 1'd0) & (p_idata_V_bv_V_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((exitcond1_reg_2438 == 1'd0) & (p_idata_V_bv_V_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_pp1_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp1_stage0_01001 = (((exitcond_reg_2578_pp1_iter5_reg == 1'd0) & (p_odata_V_bv_V_full_n == 1'b0) & (ap_enable_reg_pp1_iter6 == 1'b1)) | ((p_idata_V_bv_V_empty_n == 1'b0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (ap_predicate_op157_read_state6 == 1'b1)));
end

always @ (*) begin
    ap_block_pp1_stage0_11001 = (((exitcond_reg_2578_pp1_iter5_reg == 1'd0) & (p_odata_V_bv_V_full_n == 1'b0) & (ap_enable_reg_pp1_iter6 == 1'b1)) | ((p_idata_V_bv_V_empty_n == 1'b0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (ap_predicate_op157_read_state6 == 1'b1)));
end

always @ (*) begin
    ap_block_pp1_stage0_subdone = (((exitcond_reg_2578_pp1_iter5_reg == 1'd0) & (p_odata_V_bv_V_full_n == 1'b0) & (ap_enable_reg_pp1_iter6 == 1'b1)) | ((p_idata_V_bv_V_empty_n == 1'b0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (ap_predicate_op157_read_state6 == 1'b1)));
end

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state10_pp1_stage0_iter5 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state11_pp1_stage0_iter6 = ((exitcond_reg_2578_pp1_iter5_reg == 1'd0) & (p_odata_V_bv_V_full_n == 1'b0));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = ((exitcond1_reg_2438 == 1'd0) & (p_idata_V_bv_V_empty_n == 1'b0));
end

assign ap_block_state5_pp1_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state6_pp1_stage0_iter1 = ((p_idata_V_bv_V_empty_n == 1'b0) & (ap_predicate_op157_read_state6 == 1'b1));
end

assign ap_block_state7_pp1_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp1_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp1_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_pp1 = (ap_idle_pp1 ^ 1'b1);

always @ (*) begin
    ap_predicate_op157_read_state6 = ((p_39_reg_2613 == 1'd1) & (p_15_reg_2604 == 1'd1));
end

assign ap_ready = internal_ap_ready;

assign exitcond1_fu_424_p2 = ((ap_phi_mux_p_idata_buffer1_it_s_phi_fu_363_p4 == 8'd161) ? 1'b1 : 1'b0);

assign exitcond_fu_568_p2 = ((p_s0_v_reg_371 == 19'd307200) ? 1'b1 : 1'b0);

assign idx_urem_fu_768_p3 = ((tmp_24_fu_762_p2[0:0] === 1'b1) ? next_urem_fu_756_p2 : 19'd0);

assign next_mul1_fu_606_p2 = (38'd838861 + phi_mul1_reg_393);

assign next_mul_fu_776_p2 = (38'd838861 + phi_mul_reg_382);

assign next_urem_fu_756_p2 = (19'd1 + p_4_reg_404);

assign p_100_cast_fu_2145_p1 = p_100_fu_2137_p3;

assign p_100_fu_2137_p3 = ((p_97_fu_2040_p2[0:0] === 1'b1) ? 10'd0 : tmp_132_fu_2133_p1);

assign p_101_fu_884_p2 = ((tmp_16_fu_592_p1 > 10'd638) ? 1'b1 : 1'b0);

assign p_105_cast_fu_2241_p1 = p_105_fu_2233_p3;

assign p_105_fu_2233_p3 = ((p_88_2_fu_2149_p2[0:0] === 1'b1) ? 10'd0 : tmp_148_fu_2229_p1);

assign p_106_2_fu_1398_p2 = (p_106_reg_2665_pp1_iter2_reg | p_101_reg_2659_pp1_iter2_reg);

assign p_106_fu_890_p2 = ((p_s0_v_reg_371 > 19'd306559) ? 1'b1 : 1'b0);

assign p_107_fu_1276_p2 = (p_72_reg_2635_pp1_iter2_reg | p_106_reg_2665_pp1_iter2_reg);

assign p_110_cast_cast_fu_1394_p1 = p_110_fu_1386_p3;

assign p_110_fu_1386_p3 = ((p_107_fu_1276_p2[0:0] === 1'b1) ? 10'd0 : tmp_164_fu_1382_p1);

assign p_114_cast_cast_fu_1516_p1 = p_114_fu_1508_p3;

assign p_114_fu_1508_p3 = ((p_106_2_fu_1398_p2[0:0] === 1'b1) ? 10'd0 : tmp_180_fu_1504_p1);

assign p_115_cast_fu_2245_p1 = p_115_reg_2804;

assign p_115_fu_1855_p2 = (p_87_cast_fu_1760_p1 + p_80_cast_fu_1656_p1);

assign p_117_fu_2258_p2 = (p_115_cast_fu_2245_p1 + tmp1_cast_fu_2254_p1);

assign p_121_fu_2264_p2 = (p_64_reg_2627_pp1_iter4_reg ^ p_53_reg_2587_pp1_iter4_reg);

assign p_126_fu_2285_p3 = ((tmp_13_fu_1900_p2[0:0] === 1'b1) ? tmp_17_fu_2278_p3 : tmp_15_fu_2268_p4);

assign p_132_fu_2248_p2 = (p_95_cast1_fu_2036_p1 + p_91_cast1_fu_2007_p1);

assign p_134_cast_fu_2299_p1 = p_134_fu_2293_p2;

assign p_134_fu_2293_p2 = (p_100_cast_fu_2145_p1 + p_105_cast_fu_2241_p1);

assign p_136_fu_2306_p2 = (p_134_cast_fu_2299_p1 + tmp2_cast_fu_2303_p1);

assign p_143_fu_2347_p3 = ((tmp_13_fu_1900_p2[0:0] === 1'b1) ? tmp_35_fu_2340_p3 : tmp_14_reg_2809);

assign p_14_cast_fu_967_p1 = p_14_reg_2595_pp1_iter2_reg;

assign p_14_fu_588_p1 = p_4_reg_404[1:0];

assign p_15_fu_600_p2 = ((p_14_fu_588_p1 == 2'd0) ? 1'b1 : 1'b0);

assign p_160_fu_2368_p3 = ((tmp_13_fu_1900_p2[0:0] === 1'b1) ? tmp_37_fu_2360_p3 : tmp_31_fu_2322_p4);

assign p_26_cast_fu_622_p1 = tmp_4_fu_612_p4;

assign p_27_cast1_fu_636_p1 = tmp_20_fu_626_p4;

assign p_29_fu_680_p2 = (p_s0_v_cast_fu_580_p1 + tmp_9_fu_674_p2);

assign p_30_cast_fu_694_p3 = ((tmp_21_fu_686_p3[0:0] === 1'b1) ? 10'd1023 : 10'd0);

assign p_36_fu_702_p2 = (p_30_cast_fu_694_p3 + p_27_cast1_fu_636_p1);

assign p_38_fu_744_p2 = (18'd76639 + tmp_1_fu_738_p2);

assign p_39_fu_750_p2 = (($signed(p_26_cast_fu_622_p1) < $signed(p_38_fu_744_p2)) ? 1'b1 : 1'b0);

assign p_53_fu_584_p1 = p_4_reg_404[0:0];

assign p_54_fu_1890_p2 = (p_53_reg_2587_pp1_iter4_reg ^ 1'd1);

assign p_57_fu_840_p2 = (p_s0_v_cast_fu_580_p1 + tmp_12_fu_834_p2);

assign p_64_fu_854_p2 = (tmp_fu_782_p3 ^ tmp_25_fu_846_p3);

assign p_66_fu_1895_p2 = (p_64_reg_2627_pp1_iter4_reg ^ 1'd1);

assign p_69_fu_1904_p2 = (p_66_fu_1895_p2 & p_53_reg_2587_pp1_iter4_reg);

assign p_70_fu_1909_p2 = (p_64_reg_2627_pp1_iter4_reg & p_54_fu_1890_p2);

assign p_72_fu_860_p2 = ((tmp_18_fu_596_p1 == 11'd0) ? 1'b1 : 1'b0);

assign p_74_fu_1042_p2 = ($signed(3'd7) + $signed(p_14_cast_fu_967_p1));

assign p_76_fu_1056_p2 = ($signed(2'd3) + $signed(p_14_reg_2595_pp1_iter2_reg));

assign p_80_cast_fu_1656_p1 = p_80_fu_1649_p3;

assign p_80_fu_1649_p3 = ((p_72_reg_2635_pp1_iter3_reg[0:0] === 1'b1) ? 10'd0 : tmp_52_fu_1645_p1);

assign p_81_fu_866_p2 = ((tmp_16_fu_592_p1 < 10'd639) ? 1'b1 : 1'b0);

assign p_82_fu_1095_p2 = (3'd1 + p_14_cast_fu_967_p1);

assign p_84_fu_1101_p2 = (2'd1 + p_14_reg_2595_pp1_iter2_reg);

assign p_87_cast_fu_1760_p1 = p_87_fu_1753_p3;

assign p_87_fu_1753_p3 = ((p_81_reg_2642_pp1_iter3_reg[0:0] === 1'b1) ? tmp_69_fu_1749_p1 : 10'd0);

assign p_88_2_fu_2149_p2 = (p_88_reg_2647_pp1_iter4_reg | p_101_reg_2659_pp1_iter4_reg);

assign p_88_fu_872_p2 = ((p_s0_v_reg_371 < 19'd640) ? 1'b1 : 1'b0);

assign p_91_cast1_fu_2007_p1 = p_91_fu_2000_p3;

assign p_91_fu_2000_p3 = ((p_88_reg_2647_pp1_iter4_reg[0:0] === 1'b1) ? 10'd0 : tmp_85_fu_1996_p1);

assign p_92_fu_878_p2 = ((p_s0_v_reg_371 < 19'd306560) ? 1'b1 : 1'b0);

assign p_95_cast1_fu_2036_p1 = p_95_fu_2029_p3;

assign p_95_fu_2029_p3 = ((p_92_reg_2654_pp1_iter4_reg[0:0] === 1'b1) ? tmp_101_fu_2025_p1 : 10'd0);

assign p_97_fu_2040_p2 = (p_88_reg_2647_pp1_iter4_reg | p_72_reg_2635_pp1_iter4_reg);

assign p_Result_1_fu_1743_p2 = (tmp_67_fu_1737_p2 & tmp_66_fu_1731_p2);

assign p_Result_2_fu_1990_p2 = (tmp_83_fu_1984_p2 & tmp_82_fu_1978_p2);

assign p_Result_3_fu_2020_p2 = (tmp_99_fu_2014_p2 & tmp_98_reg_2761_pp1_iter4_reg);

assign p_Result_4_fu_1840_p2 = (tmp_115_fu_1834_p2 & tmp_114_fu_1828_p2);

assign p_Result_5_fu_2127_p2 = (tmp_130_fu_2121_p2 & tmp_129_fu_2115_p2);

assign p_Result_6_fu_2223_p2 = (tmp_146_fu_2217_p2 & tmp_145_fu_2211_p2);

assign p_Result_7_fu_1376_p2 = (tmp_162_fu_1370_p2 & tmp_161_fu_1364_p2);

assign p_Result_8_fu_1498_p2 = (tmp_178_fu_1492_p2 & tmp_177_fu_1486_p2);

assign p_Result_s_fu_1639_p2 = (tmp_50_fu_1633_p2 & tmp_49_fu_1627_p2);

assign p_Val2_1_fu_1660_p3 = ((tmp_53_reg_2708[0:0] === 1'b1) ? p_idata_window_1_v_5_fu_240 : p_idata_window_1_v_6_fu_244);

assign p_Val2_5_fu_2044_p3 = ((tmp_26_reg_2681_pp1_iter4_reg[0:0] === 1'b1) ? p_idata_window_0_v_7_fu_236 : p_idata_window_0_v_6_fu_232);

assign p_Val2_6_fu_2153_p3 = ((tmp_53_reg_2708_pp1_iter4_reg[0:0] === 1'b1) ? p_idata_window_0_v_5_fu_228 : p_idata_window_0_v_6_fu_232);

assign p_Val2_7_fu_1280_p3 = ((tmp_26_fu_1048_p3[0:0] === 1'b1) ? p_idata_window_2_v_8_fu_260 : p_idata_window_2_v_7_fu_256);

assign p_Val2_8_fu_1402_p3 = ((tmp_53_fu_1106_p3[0:0] === 1'b1) ? p_idata_window_2_v_6_fu_252 : p_idata_window_2_v_7_fu_256);

assign p_Val2_s_fu_1556_p3 = ((tmp_26_reg_2681[0:0] === 1'b1) ? p_idata_window_1_v_7_fu_248 : p_idata_window_1_v_6_fu_244);

assign p_idata_buffer1_0_5_fu_1003_p2 = (8'd1 + tmp_23_fu_983_p1);

assign p_idata_buffer1_0_6_fu_1009_p1 = p_idata_buffer1_0_5_fu_1003_p2;

assign p_idata_buffer1_1_1_fu_430_p2 = (ap_phi_mux_p_idata_buffer1_it_s_phi_fu_363_p4 + 8'd1);

assign p_idata_buffer1_1_6_fu_937_p2 = (8'd1 + tmp_22_fu_917_p1);

assign p_idata_buffer1_1_7_fu_943_p1 = p_idata_buffer1_1_6_fu_937_p2;

assign p_neg1_cast_fu_658_p1 = $signed(p_neg1_fu_652_p2);

assign p_neg1_fu_652_p2 = (19'd0 - p_shl2_cast_fu_648_p1);

assign p_neg2_cast_fu_818_p1 = $signed(p_neg2_fu_812_p2);

assign p_neg2_fu_812_p2 = (19'd0 - p_shl5_cast_fu_808_p1);

assign p_neg_cast_fu_722_p1 = $signed(p_neg_fu_716_p2);

assign p_neg_fu_716_p2 = (17'd0 - p_shl_fu_708_p3);

assign p_odata_V_bv_V_din = {{{p_160_reg_2832}, {p_143_reg_2827}}, {p_126_reg_2822}};

assign p_s0_v55_fu_574_p2 = (p_s0_v_reg_371 + 19'd1);

assign p_s0_v_cast_fu_580_p1 = p_s0_v_reg_371;

assign p_shl2_cast_fu_648_p1 = p_shl2_fu_640_p3;

assign p_shl2_fu_640_p3 = {{tmp_20_fu_626_p4}, {9'd0}};

assign p_shl3_cast_fu_670_p1 = p_shl3_fu_662_p3;

assign p_shl3_fu_662_p3 = {{tmp_20_fu_626_p4}, {7'd0}};

assign p_shl4_cast_fu_734_p1 = $signed(p_shl4_fu_726_p3);

assign p_shl4_fu_726_p3 = {{p_36_fu_702_p2}, {5'd0}};

assign p_shl5_cast_fu_808_p1 = p_shl5_fu_800_p3;

assign p_shl5_fu_800_p3 = {{tmp_11_fu_790_p4}, {9'd0}};

assign p_shl6_cast_fu_830_p1 = p_shl6_fu_822_p3;

assign p_shl6_fu_822_p3 = {{tmp_11_fu_790_p4}, {7'd0}};

assign p_shl_fu_708_p3 = {{p_36_fu_702_p2}, {7'd0}};

assign start_out = real_start;

assign tmp1_cast_fu_2254_p1 = p_132_fu_2248_p2;

assign tmp2_cast_fu_2303_p1 = tmp2_reg_2787_pp1_iter4_reg;

assign tmp2_fu_1520_p2 = (p_114_cast_cast_fu_1516_p1 + p_110_cast_cast_fu_1394_p1);

assign tmp_101_fu_2025_p1 = p_Result_3_fu_2020_p2[9:0];

assign tmp_102_fu_1258_p2 = ((Lo_assign_2_cast_fu_1160_p1 > Hi_assign_2_cast_fu_1170_p1) ? 1'b1 : 1'b0);

assign tmp_103_fu_1764_p1 = Lo_assign_2_reg_2735;

integer ap_tvar_int_0;

always @ (p_idata_window_1_v_6_fu_244) begin
    for (ap_tvar_int_0 = 40 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 39 - 0) begin
            tmp_104_fu_1767_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            tmp_104_fu_1767_p4[ap_tvar_int_0] = p_idata_window_1_v_6_fu_244[39 - ap_tvar_int_0];
        end
    end
end

assign tmp_105_fu_1777_p2 = (tmp_103_fu_1764_p1 - Hi_assign_2_reg_2741);

assign tmp_106_fu_1782_p2 = ($signed(6'd39) - $signed(tmp_103_fu_1764_p1));

assign tmp_107_fu_1788_p2 = (Hi_assign_2_reg_2741 - tmp_103_fu_1764_p1);

assign tmp_108_fu_1793_p3 = ((tmp_102_reg_2766[0:0] === 1'b1) ? tmp_105_fu_1777_p2 : tmp_107_fu_1788_p2);

assign tmp_109_fu_1800_p3 = ((tmp_102_reg_2766[0:0] === 1'b1) ? tmp_104_fu_1767_p4 : p_idata_window_1_v_6_fu_244);

assign tmp_10_fu_998_p1 = p_idata_buffer1_it_2_fu_264;

assign tmp_110_fu_1807_p3 = ((tmp_102_reg_2766[0:0] === 1'b1) ? tmp_106_fu_1782_p2 : tmp_103_fu_1764_p1);

assign tmp_111_fu_1814_p2 = ($signed(6'd39) - $signed(tmp_108_fu_1793_p3));

assign tmp_112_fu_1820_p1 = tmp_110_fu_1807_p3;

assign tmp_113_fu_1824_p1 = tmp_111_fu_1814_p2;

assign tmp_114_fu_1828_p2 = tmp_109_fu_1800_p3 >> tmp_112_fu_1820_p1;

assign tmp_115_fu_1834_p2 = 40'd1099511627775 >> tmp_113_fu_1824_p1;

assign tmp_117_fu_1264_p2 = ((Lo_assign_cast_fu_1075_p1 > Hi_assign_cast_fu_1085_p1) ? 1'b1 : 1'b0);

assign tmp_118_fu_2051_p1 = Lo_assign_reg_2687_pp1_iter4_reg;

integer ap_tvar_int_1;

always @ (p_Val2_5_fu_2044_p3) begin
    for (ap_tvar_int_1 = 40 - 1; ap_tvar_int_1 >= 0; ap_tvar_int_1 = ap_tvar_int_1 - 1) begin
        if (ap_tvar_int_1 > 39 - 0) begin
            tmp_119_fu_2054_p4[ap_tvar_int_1] = 1'b0;
        end else begin
            tmp_119_fu_2054_p4[ap_tvar_int_1] = p_Val2_5_fu_2044_p3[39 - ap_tvar_int_1];
        end
    end
end

assign tmp_11_fu_790_p4 = {{phi_mul_reg_382[37:29]}};

assign tmp_120_fu_2064_p2 = (tmp_118_fu_2051_p1 - Hi_assign_reg_2693_pp1_iter4_reg);

assign tmp_121_fu_2069_p2 = ($signed(6'd39) - $signed(tmp_118_fu_2051_p1));

assign tmp_122_fu_2075_p2 = (Hi_assign_reg_2693_pp1_iter4_reg - tmp_118_fu_2051_p1);

assign tmp_123_fu_2080_p3 = ((tmp_117_reg_2773_pp1_iter4_reg[0:0] === 1'b1) ? tmp_120_fu_2064_p2 : tmp_122_fu_2075_p2);

assign tmp_124_fu_2087_p3 = ((tmp_117_reg_2773_pp1_iter4_reg[0:0] === 1'b1) ? tmp_119_fu_2054_p4 : p_Val2_5_fu_2044_p3);

assign tmp_125_fu_2094_p3 = ((tmp_117_reg_2773_pp1_iter4_reg[0:0] === 1'b1) ? tmp_121_fu_2069_p2 : tmp_118_fu_2051_p1);

assign tmp_126_fu_2101_p2 = ($signed(6'd39) - $signed(tmp_123_fu_2080_p3));

assign tmp_127_fu_2107_p1 = tmp_125_fu_2094_p3;

assign tmp_128_fu_2111_p1 = tmp_126_fu_2101_p2;

assign tmp_129_fu_2115_p2 = tmp_124_fu_2087_p3 >> tmp_127_fu_2107_p1;

assign tmp_12_fu_834_p2 = ($signed(p_neg2_cast_fu_818_p1) - $signed(p_shl6_cast_fu_830_p1));

assign tmp_130_fu_2121_p2 = 40'd1099511627775 >> tmp_128_fu_2111_p1;

assign tmp_132_fu_2133_p1 = p_Result_5_fu_2127_p2[9:0];

assign tmp_133_fu_1270_p2 = ((Lo_assign_1_cast_fu_1128_p1 > Hi_assign_1_cast_fu_1138_p1) ? 1'b1 : 1'b0);

assign tmp_134_fu_1846_p1 = Lo_assign_1_reg_2714;

integer ap_tvar_int_2;

always @ (p_Val2_6_fu_2153_p3) begin
    for (ap_tvar_int_2 = 40 - 1; ap_tvar_int_2 >= 0; ap_tvar_int_2 = ap_tvar_int_2 - 1) begin
        if (ap_tvar_int_2 > 39 - 0) begin
            tmp_135_fu_2160_p4[ap_tvar_int_2] = 1'b0;
        end else begin
            tmp_135_fu_2160_p4[ap_tvar_int_2] = p_Val2_6_fu_2153_p3[39 - ap_tvar_int_2];
        end
    end
end

assign tmp_136_fu_2170_p2 = (tmp_134_reg_2792 - Hi_assign_1_reg_2720_pp1_iter4_reg);

assign tmp_137_fu_1849_p2 = ($signed(6'd39) - $signed(tmp_134_fu_1846_p1));

assign tmp_138_fu_2174_p2 = (Hi_assign_1_reg_2720_pp1_iter4_reg - tmp_134_reg_2792);

assign tmp_139_fu_2178_p3 = ((tmp_133_reg_2780_pp1_iter4_reg[0:0] === 1'b1) ? tmp_136_fu_2170_p2 : tmp_138_fu_2174_p2);

assign tmp_13_fu_1900_p2 = (p_64_reg_2627_pp1_iter4_reg | p_53_reg_2587_pp1_iter4_reg);

assign tmp_140_fu_2185_p3 = ((tmp_133_reg_2780_pp1_iter4_reg[0:0] === 1'b1) ? tmp_135_fu_2160_p4 : p_Val2_6_fu_2153_p3);

assign tmp_141_fu_2192_p3 = ((tmp_133_reg_2780_pp1_iter4_reg[0:0] === 1'b1) ? tmp_137_reg_2799 : tmp_134_reg_2792);

assign tmp_142_fu_2197_p2 = ($signed(6'd39) - $signed(tmp_139_fu_2178_p3));

assign tmp_143_fu_2203_p1 = tmp_141_fu_2192_p3;

assign tmp_144_fu_2207_p1 = tmp_142_fu_2197_p2;

assign tmp_145_fu_2211_p2 = tmp_140_fu_2185_p3 >> tmp_143_fu_2203_p1;

assign tmp_146_fu_2217_p2 = 40'd1099511627775 >> tmp_144_fu_2207_p1;

assign tmp_148_fu_2229_p1 = p_Result_6_fu_2223_p2[9:0];

assign tmp_149_fu_1288_p2 = ((Lo_assign_cast_fu_1075_p1 > Hi_assign_cast_fu_1085_p1) ? 1'b1 : 1'b0);

assign tmp_150_fu_1294_p1 = Lo_assign_fu_1061_p4;

integer ap_tvar_int_3;

always @ (p_Val2_7_fu_1280_p3) begin
    for (ap_tvar_int_3 = 40 - 1; ap_tvar_int_3 >= 0; ap_tvar_int_3 = ap_tvar_int_3 - 1) begin
        if (ap_tvar_int_3 > 39 - 0) begin
            tmp_151_fu_1298_p4[ap_tvar_int_3] = 1'b0;
        end else begin
            tmp_151_fu_1298_p4[ap_tvar_int_3] = p_Val2_7_fu_1280_p3[39 - ap_tvar_int_3];
        end
    end
end

assign tmp_152_fu_1308_p2 = (tmp_150_fu_1294_p1 - Hi_assign_fu_1079_p2);

assign tmp_153_fu_1314_p2 = ($signed(6'd39) - $signed(tmp_150_fu_1294_p1));

assign tmp_154_fu_1320_p2 = (Hi_assign_fu_1079_p2 - tmp_150_fu_1294_p1);

assign tmp_155_fu_1326_p3 = ((tmp_149_fu_1288_p2[0:0] === 1'b1) ? tmp_152_fu_1308_p2 : tmp_154_fu_1320_p2);

assign tmp_156_fu_1334_p3 = ((tmp_149_fu_1288_p2[0:0] === 1'b1) ? tmp_151_fu_1298_p4 : p_Val2_7_fu_1280_p3);

assign tmp_157_fu_1342_p3 = ((tmp_149_fu_1288_p2[0:0] === 1'b1) ? tmp_153_fu_1314_p2 : tmp_150_fu_1294_p1);

assign tmp_158_fu_1350_p2 = ($signed(6'd39) - $signed(tmp_155_fu_1326_p3));

assign tmp_159_fu_1356_p1 = tmp_157_fu_1342_p3;

assign tmp_15_fu_2268_p4 = {{p_117_fu_2258_p2[11:4]}};

assign tmp_160_fu_1360_p1 = tmp_158_fu_1350_p2;

assign tmp_161_fu_1364_p2 = tmp_156_fu_1334_p3 >> tmp_159_fu_1356_p1;

assign tmp_162_fu_1370_p2 = 40'd1099511627775 >> tmp_160_fu_1360_p1;

assign tmp_164_fu_1382_p1 = p_Result_7_fu_1376_p2[9:0];

assign tmp_165_fu_1410_p2 = ((Lo_assign_1_cast_fu_1128_p1 > Hi_assign_1_cast_fu_1138_p1) ? 1'b1 : 1'b0);

assign tmp_166_fu_1416_p1 = Lo_assign_1_fu_1114_p4;

integer ap_tvar_int_4;

always @ (p_Val2_8_fu_1402_p3) begin
    for (ap_tvar_int_4 = 40 - 1; ap_tvar_int_4 >= 0; ap_tvar_int_4 = ap_tvar_int_4 - 1) begin
        if (ap_tvar_int_4 > 39 - 0) begin
            tmp_167_fu_1420_p4[ap_tvar_int_4] = 1'b0;
        end else begin
            tmp_167_fu_1420_p4[ap_tvar_int_4] = p_Val2_8_fu_1402_p3[39 - ap_tvar_int_4];
        end
    end
end

assign tmp_168_fu_1430_p2 = (tmp_166_fu_1416_p1 - Hi_assign_1_fu_1132_p2);

assign tmp_169_fu_1436_p2 = ($signed(6'd39) - $signed(tmp_166_fu_1416_p1));

assign tmp_16_fu_592_p1 = p_4_reg_404[9:0];

assign tmp_170_fu_1442_p2 = (Hi_assign_1_fu_1132_p2 - tmp_166_fu_1416_p1);

assign tmp_171_fu_1448_p3 = ((tmp_165_fu_1410_p2[0:0] === 1'b1) ? tmp_168_fu_1430_p2 : tmp_170_fu_1442_p2);

assign tmp_172_fu_1456_p3 = ((tmp_165_fu_1410_p2[0:0] === 1'b1) ? tmp_167_fu_1420_p4 : p_Val2_8_fu_1402_p3);

assign tmp_173_fu_1464_p3 = ((tmp_165_fu_1410_p2[0:0] === 1'b1) ? tmp_169_fu_1436_p2 : tmp_166_fu_1416_p1);

assign tmp_174_fu_1472_p2 = ($signed(6'd39) - $signed(tmp_171_fu_1448_p3));

assign tmp_175_fu_1478_p1 = tmp_173_fu_1464_p3;

assign tmp_176_fu_1482_p1 = tmp_174_fu_1472_p2;

assign tmp_177_fu_1486_p2 = tmp_172_fu_1456_p3 >> tmp_175_fu_1478_p1;

assign tmp_178_fu_1492_p2 = 40'd1099511627775 >> tmp_176_fu_1482_p1;

assign tmp_17_fu_2278_p3 = ((p_121_fu_2264_p2[0:0] === 1'b1) ? tmp_14_reg_2809 : tmp_15_fu_2268_p4);

assign tmp_180_fu_1504_p1 = p_Result_8_fu_1498_p2[9:0];

assign tmp_18_fu_596_p1 = p_4_reg_404[10:0];

assign tmp_1_fu_738_p2 = ($signed(p_neg_cast_fu_722_p1) - $signed(p_shl4_cast_fu_734_p1));

assign tmp_20_fu_626_p4 = {{phi_mul1_reg_393[37:29]}};

assign tmp_21_cast_fu_921_p2 = (8'd99 + tmp_22_fu_917_p1);

assign tmp_21_fu_686_p3 = p_29_fu_680_p2[32'd19];

assign tmp_22_fu_917_p1 = p_idata_buffer1_it_1_fu_268[7:0];

assign tmp_23_fu_983_p1 = p_idata_buffer1_it_2_fu_264[7:0];

assign tmp_24_fu_762_p2 = ((next_urem_fu_756_p2 < 19'd640) ? 1'b1 : 1'b0);

assign tmp_25_fu_846_p3 = p_57_fu_840_p2[32'd19];

assign tmp_26_fu_1048_p3 = p_74_fu_1042_p2[32'd2];

assign tmp_27_cast_fu_987_p2 = (8'd99 + tmp_23_fu_983_p1);

assign tmp_27_fu_1089_p2 = ((Lo_assign_cast_fu_1075_p1 > Hi_assign_cast_fu_1085_p1) ? 1'b1 : 1'b0);

assign tmp_28_fu_1563_p1 = Lo_assign_reg_2687;

integer ap_tvar_int_5;

always @ (p_Val2_s_fu_1556_p3) begin
    for (ap_tvar_int_5 = 40 - 1; ap_tvar_int_5 >= 0; ap_tvar_int_5 = ap_tvar_int_5 - 1) begin
        if (ap_tvar_int_5 > 39 - 0) begin
            tmp_29_fu_1566_p4[ap_tvar_int_5] = 1'b0;
        end else begin
            tmp_29_fu_1566_p4[ap_tvar_int_5] = p_Val2_s_fu_1556_p3[39 - ap_tvar_int_5];
        end
    end
end

assign tmp_2_cast_fu_436_p2 = (ap_phi_mux_p_idata_buffer1_it_s_phi_fu_363_p4 + 8'd99);

assign tmp_2_fu_932_p1 = p_idata_buffer1_it_1_fu_268;

assign tmp_30_fu_2312_p4 = {{p_132_fu_2248_p2[10:3]}};

assign tmp_31_fu_2322_p4 = {{p_136_fu_2306_p2[11:4]}};

assign tmp_32_fu_2332_p3 = ((p_70_fu_1909_p2[0:0] === 1'b1) ? tmp_30_fu_2312_p4 : tmp_31_fu_2322_p4);

assign tmp_33_fu_1576_p2 = (tmp_28_fu_1563_p1 - Hi_assign_reg_2693);

assign tmp_34_fu_1581_p2 = ($signed(6'd39) - $signed(tmp_28_fu_1563_p1));

assign tmp_35_fu_2340_p3 = ((p_69_fu_1904_p2[0:0] === 1'b1) ? tmp_19_reg_2816 : tmp_32_fu_2332_p3);

assign tmp_36_fu_2354_p3 = ((p_70_fu_1909_p2[0:0] === 1'b1) ? tmp_19_reg_2816 : tmp_14_reg_2809);

assign tmp_37_fu_2360_p3 = ((p_69_fu_1904_p2[0:0] === 1'b1) ? tmp_30_fu_2312_p4 : tmp_36_fu_2354_p3);

assign tmp_40_fu_1587_p2 = (Hi_assign_reg_2693 - tmp_28_fu_1563_p1);

assign tmp_41_fu_1592_p3 = ((tmp_27_reg_2701[0:0] === 1'b1) ? tmp_33_fu_1576_p2 : tmp_40_fu_1587_p2);

assign tmp_42_fu_1599_p3 = ((tmp_27_reg_2701[0:0] === 1'b1) ? tmp_29_fu_1566_p4 : p_Val2_s_fu_1556_p3);

assign tmp_43_fu_1606_p3 = ((tmp_27_reg_2701[0:0] === 1'b1) ? tmp_34_fu_1581_p2 : tmp_28_fu_1563_p1);

assign tmp_44_fu_1613_p2 = ($signed(6'd39) - $signed(tmp_41_fu_1592_p3));

assign tmp_47_fu_1619_p1 = tmp_43_fu_1606_p3;

assign tmp_48_fu_1623_p1 = tmp_44_fu_1613_p2;

assign tmp_49_fu_1627_p2 = tmp_42_fu_1599_p3 >> tmp_47_fu_1619_p1;

assign tmp_4_fu_612_p4 = {{p_4_reg_404[9:2]}};

assign tmp_50_fu_1633_p2 = 40'd1099511627775 >> tmp_48_fu_1623_p1;

assign tmp_52_fu_1645_p1 = p_Result_s_fu_1639_p2[9:0];

assign tmp_53_fu_1106_p3 = p_82_fu_1095_p2[32'd2];

assign tmp_54_fu_1142_p2 = ((Lo_assign_1_cast_fu_1128_p1 > Hi_assign_1_cast_fu_1138_p1) ? 1'b1 : 1'b0);

assign tmp_55_fu_1667_p1 = Lo_assign_1_reg_2714;

integer ap_tvar_int_6;

always @ (p_Val2_1_fu_1660_p3) begin
    for (ap_tvar_int_6 = 40 - 1; ap_tvar_int_6 >= 0; ap_tvar_int_6 = ap_tvar_int_6 - 1) begin
        if (ap_tvar_int_6 > 39 - 0) begin
            tmp_56_fu_1670_p4[ap_tvar_int_6] = 1'b0;
        end else begin
            tmp_56_fu_1670_p4[ap_tvar_int_6] = p_Val2_1_fu_1660_p3[39 - ap_tvar_int_6];
        end
    end
end

assign tmp_57_fu_1680_p2 = (tmp_55_fu_1667_p1 - Hi_assign_1_reg_2720);

assign tmp_58_fu_1685_p2 = ($signed(6'd39) - $signed(tmp_55_fu_1667_p1));

assign tmp_59_fu_1691_p2 = (Hi_assign_1_reg_2720 - tmp_55_fu_1667_p1);

assign tmp_5_fu_442_p1 = tmp_2_cast_fu_436_p2;

assign tmp_60_fu_1696_p3 = ((tmp_54_reg_2728[0:0] === 1'b1) ? tmp_57_fu_1680_p2 : tmp_59_fu_1691_p2);

assign tmp_61_fu_1703_p3 = ((tmp_54_reg_2728[0:0] === 1'b1) ? tmp_56_fu_1670_p4 : p_Val2_1_fu_1660_p3);

assign tmp_62_fu_1710_p3 = ((tmp_54_reg_2728[0:0] === 1'b1) ? tmp_58_fu_1685_p2 : tmp_55_fu_1667_p1);

assign tmp_63_fu_1717_p2 = ($signed(6'd39) - $signed(tmp_60_fu_1696_p3));

assign tmp_64_fu_1723_p1 = tmp_62_fu_1710_p3;

assign tmp_65_fu_1727_p1 = tmp_63_fu_1717_p2;

assign tmp_66_fu_1731_p2 = tmp_61_fu_1703_p3 >> tmp_64_fu_1723_p1;

assign tmp_67_fu_1737_p2 = 40'd1099511627775 >> tmp_65_fu_1727_p1;

assign tmp_69_fu_1749_p1 = p_Result_1_fu_1743_p2[9:0];

assign tmp_6_fu_498_p1 = p_idata_buffer1_it_s_reg_359;

assign tmp_70_fu_1174_p2 = ((Lo_assign_2_cast_fu_1160_p1 > Hi_assign_2_cast_fu_1170_p1) ? 1'b1 : 1'b0);

assign tmp_71_fu_1914_p1 = Lo_assign_2_reg_2735_pp1_iter4_reg;

integer ap_tvar_int_7;

always @ (p_idata_window_0_v_6_fu_232) begin
    for (ap_tvar_int_7 = 40 - 1; ap_tvar_int_7 >= 0; ap_tvar_int_7 = ap_tvar_int_7 - 1) begin
        if (ap_tvar_int_7 > 39 - 0) begin
            tmp_72_fu_1917_p4[ap_tvar_int_7] = 1'b0;
        end else begin
            tmp_72_fu_1917_p4[ap_tvar_int_7] = p_idata_window_0_v_6_fu_232[39 - ap_tvar_int_7];
        end
    end
end

assign tmp_73_fu_1927_p2 = (tmp_71_fu_1914_p1 - Hi_assign_2_reg_2741_pp1_iter4_reg);

assign tmp_74_fu_1932_p2 = ($signed(6'd39) - $signed(tmp_71_fu_1914_p1));

assign tmp_75_fu_1938_p2 = (Hi_assign_2_reg_2741_pp1_iter4_reg - tmp_71_fu_1914_p1);

assign tmp_76_fu_1943_p3 = ((tmp_70_reg_2749_pp1_iter4_reg[0:0] === 1'b1) ? tmp_73_fu_1927_p2 : tmp_75_fu_1938_p2);

assign tmp_77_fu_1950_p3 = ((tmp_70_reg_2749_pp1_iter4_reg[0:0] === 1'b1) ? tmp_72_fu_1917_p4 : p_idata_window_0_v_6_fu_232);

assign tmp_78_fu_1957_p3 = ((tmp_70_reg_2749_pp1_iter4_reg[0:0] === 1'b1) ? tmp_74_fu_1932_p2 : tmp_71_fu_1914_p1);

assign tmp_79_fu_1964_p2 = ($signed(6'd39) - $signed(tmp_76_fu_1943_p3));

assign tmp_7_fu_993_p1 = tmp_27_cast_fu_987_p2;

assign tmp_80_fu_1970_p1 = tmp_78_fu_1957_p3;

assign tmp_81_fu_1974_p1 = tmp_79_fu_1964_p2;

assign tmp_82_fu_1978_p2 = tmp_77_fu_1950_p3 >> tmp_80_fu_1970_p1;

assign tmp_83_fu_1984_p2 = 40'd1099511627775 >> tmp_81_fu_1974_p1;

assign tmp_85_fu_1996_p1 = p_Result_2_fu_1990_p2[9:0];

assign tmp_86_fu_1180_p2 = ((Lo_assign_2_cast_fu_1160_p1 > Hi_assign_2_cast_fu_1170_p1) ? 1'b1 : 1'b0);

assign tmp_87_fu_1186_p1 = Lo_assign_2_fu_1148_p4;

integer ap_tvar_int_8;

always @ (p_idata_window_2_v_7_fu_256) begin
    for (ap_tvar_int_8 = 40 - 1; ap_tvar_int_8 >= 0; ap_tvar_int_8 = ap_tvar_int_8 - 1) begin
        if (ap_tvar_int_8 > 39 - 0) begin
            tmp_88_fu_1190_p4[ap_tvar_int_8] = 1'b0;
        end else begin
            tmp_88_fu_1190_p4[ap_tvar_int_8] = p_idata_window_2_v_7_fu_256[39 - ap_tvar_int_8];
        end
    end
end

assign tmp_89_fu_1200_p2 = (tmp_87_fu_1186_p1 - Hi_assign_2_fu_1164_p2);

assign tmp_90_fu_1206_p2 = ($signed(6'd39) - $signed(tmp_87_fu_1186_p1));

assign tmp_91_fu_1212_p2 = (Hi_assign_2_fu_1164_p2 - tmp_87_fu_1186_p1);

assign tmp_92_fu_1218_p3 = ((tmp_86_fu_1180_p2[0:0] === 1'b1) ? tmp_89_fu_1200_p2 : tmp_91_fu_1212_p2);

assign tmp_93_fu_1226_p3 = ((tmp_86_fu_1180_p2[0:0] === 1'b1) ? tmp_88_fu_1190_p4 : p_idata_window_2_v_7_fu_256);

assign tmp_94_fu_1234_p3 = ((tmp_86_fu_1180_p2[0:0] === 1'b1) ? tmp_90_fu_1206_p2 : tmp_87_fu_1186_p1);

assign tmp_95_fu_1242_p2 = ($signed(6'd39) - $signed(tmp_92_fu_1218_p3));

assign tmp_96_fu_1248_p1 = tmp_94_fu_1234_p3;

assign tmp_97_fu_2011_p1 = tmp_95_reg_2756_pp1_iter4_reg;

assign tmp_98_fu_1252_p2 = tmp_93_fu_1226_p3 >> tmp_96_fu_1248_p1;

assign tmp_99_fu_2014_p2 = 40'd1099511627775 >> tmp_97_fu_2011_p1;

assign tmp_9_fu_674_p2 = ($signed(p_neg1_cast_fu_658_p1) - $signed(p_shl3_cast_fu_670_p1));

assign tmp_fu_782_p3 = phi_mul_reg_382[32'd29];

assign tmp_s_fu_927_p1 = tmp_21_cast_fu_921_p2;

always @ (posedge ap_clk) begin
    Lo_assign_reg_2687[0] <= 1'b0;
    Lo_assign_reg_2687_pp1_iter4_reg[0] <= 1'b0;
    Hi_assign_reg_2693[0] <= 1'b1;
    Hi_assign_reg_2693_pp1_iter4_reg[0] <= 1'b1;
    Lo_assign_1_reg_2714[0] <= 1'b0;
    Hi_assign_1_reg_2720[0] <= 1'b1;
    Hi_assign_1_reg_2720_pp1_iter4_reg[0] <= 1'b1;
    Lo_assign_2_reg_2735[0] <= 1'b0;
    Lo_assign_2_reg_2735_pp1_iter4_reg[0] <= 1'b0;
    Hi_assign_2_reg_2741[0] <= 1'b1;
    Hi_assign_2_reg_2741_pp1_iter4_reg[0] <= 1'b1;
    tmp_95_reg_2756[0] <= 1'b0;
    tmp_95_reg_2756_pp1_iter4_reg[0] <= 1'b0;
    tmp_134_reg_2792[0] <= 1'b0;
    tmp_134_reg_2792[5] <= 1'b0;
    tmp_137_reg_2799[0] <= 1'b1;
    p_idata_buffer1_it_2_fu_264[31:8] <= 24'b000000000000000000000000;
    p_idata_buffer1_it_1_fu_268[31:8] <= 24'b000000000000000000000000;
end

endmodule //odata
