// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module odata (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        p_demosaic_V_bv_V_dout,
        p_demosaic_V_bv_V_empty_n,
        p_demosaic_V_bv_V_read,
        p_odata_V_bv_V_din,
        p_odata_V_bv_V_full_n,
        p_odata_V_bv_V_write
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_pp0_stage0 = 5'd2;
parameter    ap_ST_fsm_state4 = 5'd4;
parameter    ap_ST_fsm_pp1_stage0 = 5'd8;
parameter    ap_ST_fsm_state21 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [7:0] p_demosaic_V_bv_V_dout;
input   p_demosaic_V_bv_V_empty_n;
output   p_demosaic_V_bv_V_read;
output  [31:0] p_odata_V_bv_V_din;
input   p_odata_V_bv_V_full_n;
output   p_odata_V_bv_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg p_demosaic_V_bv_V_read;
reg p_odata_V_bv_V_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    p_demosaic_V_bv_V_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] exitcond1_reg_1033;
wire    ap_CS_fsm_pp1_stage0;
reg    ap_enable_reg_pp1_iter1;
wire    ap_block_pp1_stage0;
reg   [0:0] exitcond_reg_1061;
reg   [0:0] p_221_reg_1070;
reg    p_odata_V_bv_V_blk_n;
reg    ap_enable_reg_pp1_iter15;
reg   [0:0] p_401_reg_1115;
reg   [0:0] p_258_reg_1079;
reg   [0:0] p_258_reg_1079_pp1_iter14_reg;
reg   [1:0] p_prefill_demosaic_reg_195;
reg   [7:0] p_demosaic_window_1_1_reg_206;
reg   [7:0] ret_v_bv_V_reg_218;
reg   [7:0] p_demosaic_window_0_reg_231;
reg   [7:0] p_demosaic_window_v_reg_244;
reg   [19:0] p_s0_v_reg_257;
reg   [19:0] p_228_reg_268;
reg   [7:0] p_demosaic_window_1_4_reg_279;
reg   [7:0] p_demosaic_window_1_4_reg_279_pp1_iter2_reg;
wire    ap_block_state5_pp1_stage0_iter0;
reg    ap_predicate_op81_read_state6;
reg    ap_block_state6_pp1_stage0_iter1;
wire    ap_block_state7_pp1_stage0_iter2;
wire    ap_block_state8_pp1_stage0_iter3;
wire    ap_block_state9_pp1_stage0_iter4;
wire    ap_block_state10_pp1_stage0_iter5;
wire    ap_block_state11_pp1_stage0_iter6;
wire    ap_block_state12_pp1_stage0_iter7;
wire    ap_block_state13_pp1_stage0_iter8;
wire    ap_block_state14_pp1_stage0_iter9;
wire    ap_block_state15_pp1_stage0_iter10;
wire    ap_block_state16_pp1_stage0_iter11;
wire    ap_block_state17_pp1_stage0_iter12;
wire    ap_block_state18_pp1_stage0_iter13;
wire    ap_block_state19_pp1_stage0_iter14;
reg    ap_predicate_op187_write_state20;
reg    ap_block_state20_pp1_stage0_iter15;
reg    ap_block_pp1_stage0_11001;
reg   [7:0] p_demosaic_window_1_4_reg_279_pp1_iter3_reg;
reg   [7:0] p_demosaic_window_1_4_reg_279_pp1_iter4_reg;
reg   [7:0] p_demosaic_window_1_4_reg_279_pp1_iter5_reg;
reg   [7:0] p_demosaic_window_1_4_reg_279_pp1_iter6_reg;
reg   [7:0] p_demosaic_window_1_4_reg_279_pp1_iter7_reg;
reg   [7:0] p_demosaic_window_1_4_reg_279_pp1_iter8_reg;
reg   [7:0] p_demosaic_window_1_4_reg_279_pp1_iter9_reg;
reg   [7:0] p_demosaic_window_1_4_reg_279_pp1_iter10_reg;
reg   [7:0] p_demosaic_window_1_4_reg_279_pp1_iter11_reg;
reg   [7:0] p_demosaic_window_1_4_reg_279_pp1_iter12_reg;
reg   [7:0] p_demosaic_window_1_4_reg_279_pp1_iter13_reg;
reg   [7:0] ret_v_bv_V_1_reg_290;
reg   [7:0] ret_v_bv_V_1_reg_290_pp1_iter2_reg;
reg   [7:0] ret_v_bv_V_1_reg_290_pp1_iter3_reg;
reg   [7:0] ret_v_bv_V_1_reg_290_pp1_iter4_reg;
reg   [7:0] ret_v_bv_V_1_reg_290_pp1_iter5_reg;
reg   [7:0] ret_v_bv_V_1_reg_290_pp1_iter6_reg;
reg   [7:0] ret_v_bv_V_1_reg_290_pp1_iter7_reg;
reg   [7:0] ret_v_bv_V_1_reg_290_pp1_iter8_reg;
reg   [7:0] ret_v_bv_V_1_reg_290_pp1_iter9_reg;
reg   [7:0] ret_v_bv_V_1_reg_290_pp1_iter10_reg;
reg   [7:0] ret_v_bv_V_1_reg_290_pp1_iter11_reg;
reg   [7:0] ret_v_bv_V_1_reg_290_pp1_iter12_reg;
reg   [7:0] ret_v_bv_V_1_reg_290_pp1_iter13_reg;
reg   [7:0] p_demosaic_window_0_1_reg_302;
reg   [7:0] p_demosaic_window_0_1_reg_302_pp1_iter2_reg;
reg   [7:0] p_demosaic_window_0_1_reg_302_pp1_iter3_reg;
reg   [7:0] p_demosaic_window_0_1_reg_302_pp1_iter4_reg;
reg   [7:0] p_demosaic_window_0_1_reg_302_pp1_iter5_reg;
reg   [7:0] p_demosaic_window_0_1_reg_302_pp1_iter6_reg;
reg   [7:0] p_demosaic_window_0_1_reg_302_pp1_iter7_reg;
reg   [7:0] p_demosaic_window_0_1_reg_302_pp1_iter8_reg;
reg   [7:0] p_demosaic_window_0_1_reg_302_pp1_iter9_reg;
reg   [7:0] p_demosaic_window_0_1_reg_302_pp1_iter10_reg;
reg   [7:0] p_demosaic_window_0_1_reg_302_pp1_iter11_reg;
reg   [7:0] p_demosaic_window_0_1_reg_302_pp1_iter12_reg;
reg   [7:0] p_demosaic_window_0_1_reg_302_pp1_iter13_reg;
reg   [7:0] p_Val2_7_reg_314;
wire   [0:0] exitcond1_fu_329_p2;
wire    ap_block_state2_pp0_stage0_iter0;
reg    ap_block_state3_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
wire   [1:0] p_prefill_demosaic_1_fu_335_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] exitcond_fu_351_p2;
reg   [0:0] exitcond_reg_1061_pp1_iter1_reg;
reg   [0:0] exitcond_reg_1061_pp1_iter2_reg;
reg   [0:0] exitcond_reg_1061_pp1_iter3_reg;
reg   [0:0] exitcond_reg_1061_pp1_iter4_reg;
reg   [0:0] exitcond_reg_1061_pp1_iter5_reg;
reg   [0:0] exitcond_reg_1061_pp1_iter6_reg;
reg   [0:0] exitcond_reg_1061_pp1_iter7_reg;
reg   [0:0] exitcond_reg_1061_pp1_iter8_reg;
reg   [0:0] exitcond_reg_1061_pp1_iter9_reg;
reg   [0:0] exitcond_reg_1061_pp1_iter10_reg;
reg   [0:0] exitcond_reg_1061_pp1_iter11_reg;
reg   [0:0] exitcond_reg_1061_pp1_iter12_reg;
reg   [0:0] exitcond_reg_1061_pp1_iter13_reg;
wire   [19:0] p_s0_v80_fu_357_p2;
reg    ap_enable_reg_pp1_iter0;
wire   [0:0] p_221_fu_363_p2;
wire   [10:0] tmp_14_fu_373_p1;
wire   [0:0] p_258_fu_444_p2;
reg   [0:0] p_258_reg_1079_pp1_iter1_reg;
reg   [0:0] p_258_reg_1079_pp1_iter2_reg;
reg   [0:0] p_258_reg_1079_pp1_iter3_reg;
reg   [0:0] p_258_reg_1079_pp1_iter4_reg;
reg   [0:0] p_258_reg_1079_pp1_iter5_reg;
reg   [0:0] p_258_reg_1079_pp1_iter6_reg;
reg   [0:0] p_258_reg_1079_pp1_iter7_reg;
reg   [0:0] p_258_reg_1079_pp1_iter8_reg;
reg   [0:0] p_258_reg_1079_pp1_iter9_reg;
reg   [0:0] p_258_reg_1079_pp1_iter10_reg;
reg   [0:0] p_258_reg_1079_pp1_iter11_reg;
reg   [0:0] p_258_reg_1079_pp1_iter12_reg;
reg   [0:0] p_258_reg_1079_pp1_iter13_reg;
wire   [19:0] idx_urem_fu_462_p3;
reg   [7:0] p_demosaic_window_1_5_reg_1089;
reg   [7:0] p_demosaic_window_1_5_reg_1089_pp1_iter2_reg;
reg   [7:0] p_demosaic_window_1_5_reg_1089_pp1_iter3_reg;
reg   [7:0] p_demosaic_window_1_5_reg_1089_pp1_iter4_reg;
reg   [7:0] p_demosaic_window_1_5_reg_1089_pp1_iter5_reg;
reg   [7:0] p_demosaic_window_1_5_reg_1089_pp1_iter6_reg;
reg   [7:0] p_demosaic_window_1_5_reg_1089_pp1_iter7_reg;
reg   [7:0] p_demosaic_window_1_5_reg_1089_pp1_iter8_reg;
reg   [7:0] p_demosaic_window_1_5_reg_1089_pp1_iter9_reg;
reg   [7:0] p_demosaic_window_1_5_reg_1089_pp1_iter10_reg;
reg   [7:0] p_demosaic_window_1_5_reg_1089_pp1_iter11_reg;
reg   [7:0] p_demosaic_window_1_5_reg_1089_pp1_iter12_reg;
reg   [7:0] p_demosaic_window_1_5_reg_1089_pp1_iter13_reg;
reg   [7:0] p_demosaic_window_1_6_reg_1095;
reg   [7:0] p_demosaic_window_1_6_reg_1095_pp1_iter3_reg;
reg   [7:0] p_demosaic_window_1_6_reg_1095_pp1_iter4_reg;
reg   [7:0] p_demosaic_window_1_6_reg_1095_pp1_iter5_reg;
reg   [7:0] p_demosaic_window_1_6_reg_1095_pp1_iter6_reg;
reg   [7:0] p_demosaic_window_1_6_reg_1095_pp1_iter7_reg;
reg   [7:0] p_demosaic_window_1_6_reg_1095_pp1_iter8_reg;
reg   [7:0] p_demosaic_window_1_6_reg_1095_pp1_iter9_reg;
reg   [7:0] p_demosaic_window_1_6_reg_1095_pp1_iter10_reg;
reg   [7:0] p_demosaic_window_1_6_reg_1095_pp1_iter11_reg;
reg   [7:0] p_demosaic_window_1_6_reg_1095_pp1_iter12_reg;
reg   [7:0] p_demosaic_window_1_6_reg_1095_pp1_iter13_reg;
reg   [9:0] tmp_23_reg_1100;
reg   [9:0] tmp_25_reg_1105;
wire   [31:0] p_odata_window_vs_s_fu_929_p3;
reg   [31:0] p_odata_window_vs_s_reg_1110;
wire   [0:0] p_401_fu_937_p2;
reg    ap_block_state1;
reg    ap_block_pp0_stage0_subdone;
wire    ap_CS_fsm_state4;
reg    ap_block_pp1_stage0_subdone;
reg    ap_enable_reg_pp1_iter2;
reg    ap_condition_pp1_exit_iter1_state6;
reg    ap_enable_reg_pp1_iter3;
reg    ap_enable_reg_pp1_iter4;
reg    ap_enable_reg_pp1_iter5;
reg    ap_enable_reg_pp1_iter6;
reg    ap_enable_reg_pp1_iter7;
reg    ap_enable_reg_pp1_iter8;
reg    ap_enable_reg_pp1_iter9;
reg    ap_enable_reg_pp1_iter10;
reg    ap_enable_reg_pp1_iter11;
reg    ap_enable_reg_pp1_iter12;
reg    ap_enable_reg_pp1_iter13;
reg    ap_enable_reg_pp1_iter14;
reg   [7:0] ap_phi_mux_p_Val2_7_phi_fu_317_p4;
reg    ap_block_pp1_stage0_01001;
reg   [7:0] p_demosaic_window_1_fu_170;
reg   [31:0] p_Val2_s_fu_174;
reg   [7:0] p_329_fu_178;
wire   [2:0] grp_fu_377_p1;
wire   [23:0] mul_fu_948_p2;
wire   [10:0] tmp_6_fu_387_p4;
wire   [9:0] tmp_7_fu_407_p4;
wire   [11:0] p_249_cast1_fu_396_p1;
wire   [11:0] p_shl_fu_416_p3;
wire   [11:0] tmp_2_fu_424_p2;
wire   [11:0] tmp_13_fu_369_p1;
wire   [11:0] p_251_fu_430_p2;
wire   [0:0] tmp_21_fu_400_p3;
wire   [0:0] tmp_22_fu_436_p3;
wire   [19:0] next_urem_fu_450_p2;
wire   [0:0] tmp_27_fu_456_p2;
wire   [17:0] p_292_fu_481_p3;
wire  signed [26:0] p_295_fu_957_p2;
wire   [16:0] tmp_1_fu_493_p4;
wire   [17:0] p_300_fu_506_p3;
wire  signed [27:0] p_303_fu_964_p2;
wire   [17:0] tmp_8_fu_518_p4;
wire   [16:0] p_308_fu_531_p3;
wire  signed [18:0] p_cast7_fu_502_p1;
wire   [18:0] p_308_cast_cast_fu_539_p1;
wire   [18:0] tmp2_fu_543_p2;
wire  signed [19:0] tmp2_cast_fu_549_p1;
wire  signed [19:0] p_cast6_fu_527_p1;
wire   [19:0] p_313_fu_553_p2;
wire   [16:0] p_353_fu_569_p3;
wire  signed [27:0] p_362_fu_971_p2;
wire   [17:0] tmp_12_fu_581_p4;
wire   [17:0] p_368_fu_594_p3;
wire  signed [25:0] p_371_fu_978_p2;
wire   [15:0] tmp_15_fu_606_p4;
wire   [18:0] p_353_cast_cast_fu_577_p1;
wire  signed [18:0] p_cast_fu_615_p1;
wire   [18:0] tmp4_fu_619_p2;
wire  signed [19:0] tmp4_cast_fu_625_p1;
wire  signed [19:0] p_cast5_fu_590_p1;
wire   [19:0] p_374_fu_629_p2;
wire   [10:0] grp_fu_377_p2;
wire   [0:0] p_248_fu_652_p3;
wire   [0:0] p_260_fu_660_p2;
wire   [26:0] p_s_fu_985_p2;
wire   [16:0] tmp_9_fu_675_p4;
wire   [27:0] p_8_fu_992_p2;
wire   [24:0] p_6_fu_999_p2;
wire   [14:0] tmp_s_fu_705_p4;
wire   [17:0] p_276_cast_fu_692_p4;
wire   [17:0] p_284_cast_fu_714_p1;
wire   [17:0] tmp1_fu_718_p2;
wire   [17:0] p_269_cast_fu_684_p1;
wire   [17:0] p_285_fu_724_p2;
wire   [0:0] tmp_i_fu_730_p2;
wire   [7:0] tmp_fu_736_p4;
wire  signed [10:0] tmp_14_cast_fu_754_p1;
wire   [10:0] p_315_fu_757_p2;
wire   [0:0] tmp_i1_fu_763_p2;
wire   [10:0] p_316_fu_769_p3;
wire   [0:0] tmp_i2_fu_777_p2;
wire   [7:0] tmp_24_fu_783_p1;
wire   [26:0] p_19_fu_1006_p2;
wire   [16:0] tmp_10_fu_799_p4;
wire   [27:0] p_20_fu_1013_p2;
wire   [24:0] p_21_fu_1020_p2;
wire   [14:0] tmp_11_fu_827_p4;
wire   [17:0] p_336_cast_fu_815_p4;
wire   [17:0] p_345_cast_fu_836_p1;
wire   [17:0] tmp3_fu_840_p2;
wire   [17:0] p_328_cast_fu_808_p1;
wire   [17:0] p_346_fu_846_p2;
wire   [0:0] tmp_i3_fu_852_p2;
wire   [7:0] tmp_5_fu_858_p4;
wire  signed [10:0] tmp_20_cast_fu_876_p1;
wire   [10:0] p_376_fu_879_p2;
wire   [0:0] tmp_i4_fu_885_p2;
wire   [10:0] p_377_fu_891_p3;
wire   [0:0] tmp_i5_fu_899_p2;
wire   [7:0] tmp_26_fu_905_p1;
wire   [7:0] p_379_fu_909_p3;
wire   [7:0] p_350_fu_868_p3;
wire   [7:0] p_318_fu_787_p3;
wire   [7:0] p_289_fu_746_p3;
wire   [0:0] p_260_2_fu_665_p2;
wire   [31:0] p_Result_s_fu_917_p5;
wire   [2:0] tmp_19_fu_648_p1;
wire   [12:0] mul_fu_948_p0;
wire   [10:0] mul_fu_948_p1;
wire  signed [8:0] p_295_fu_957_p0;
wire   [17:0] p_295_fu_957_p1;
wire  signed [9:0] p_303_fu_964_p0;
wire   [17:0] p_303_fu_964_p1;
wire   [27:0] p_301_cast_fu_514_p1;
wire  signed [9:0] p_362_fu_971_p0;
wire   [17:0] p_362_fu_971_p1;
wire  signed [7:0] p_371_fu_978_p0;
wire   [17:0] p_371_fu_978_p1;
wire   [19:0] p_s_fu_985_p0;
wire   [7:0] p_s_fu_985_p1;
wire   [20:0] p_8_fu_992_p0;
wire   [7:0] p_8_fu_992_p1;
wire   [17:0] p_6_fu_999_p0;
wire   [7:0] p_6_fu_999_p1;
wire   [19:0] p_19_fu_1006_p0;
wire   [7:0] p_19_fu_1006_p1;
wire   [20:0] p_20_fu_1013_p0;
wire   [7:0] p_20_fu_1013_p1;
wire   [17:0] p_21_fu_1020_p0;
wire   [7:0] p_21_fu_1020_p1;
reg    grp_fu_377_ce;
wire    ap_CS_fsm_state21;
reg   [4:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_idle_pp1;
wire    ap_enable_pp1;
wire   [23:0] mul_fu_948_p10;
wire   [26:0] p_19_fu_1006_p10;
wire   [27:0] p_20_fu_1013_p10;
wire   [24:0] p_21_fu_1020_p10;
wire   [26:0] p_295_fu_957_p10;
wire   [25:0] p_371_fu_978_p10;
wire   [24:0] p_6_fu_999_p10;
wire   [27:0] p_8_fu_992_p10;
wire   [26:0] p_s_fu_985_p10;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 5'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp1_iter1 = 1'b0;
#0 ap_enable_reg_pp1_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp1_iter0 = 1'b0;
#0 ap_enable_reg_pp1_iter2 = 1'b0;
#0 ap_enable_reg_pp1_iter3 = 1'b0;
#0 ap_enable_reg_pp1_iter4 = 1'b0;
#0 ap_enable_reg_pp1_iter5 = 1'b0;
#0 ap_enable_reg_pp1_iter6 = 1'b0;
#0 ap_enable_reg_pp1_iter7 = 1'b0;
#0 ap_enable_reg_pp1_iter8 = 1'b0;
#0 ap_enable_reg_pp1_iter9 = 1'b0;
#0 ap_enable_reg_pp1_iter10 = 1'b0;
#0 ap_enable_reg_pp1_iter11 = 1'b0;
#0 ap_enable_reg_pp1_iter12 = 1'b0;
#0 ap_enable_reg_pp1_iter13 = 1'b0;
#0 ap_enable_reg_pp1_iter14 = 1'b0;
end

demosaic_root_urehbi #(
    .ID( 1 ),
    .NUM_STAGE( 15 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 11 ))
demosaic_root_urehbi_U20(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_14_fu_373_p1),
    .din1(grp_fu_377_p1),
    .ce(grp_fu_377_ce),
    .dout(grp_fu_377_p2)
);

demosaic_root_mulg8j #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 13 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 24 ))
demosaic_root_mulg8j_U21(
    .din0(mul_fu_948_p0),
    .din1(mul_fu_948_p1),
    .dout(mul_fu_948_p2)
);

demosaic_root_mulibs #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 27 ))
demosaic_root_mulibs_U22(
    .din0(p_295_fu_957_p0),
    .din1(p_295_fu_957_p1),
    .dout(p_295_fu_957_p2)
);

demosaic_root_muljbC #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 28 ))
demosaic_root_muljbC_U23(
    .din0(p_303_fu_964_p0),
    .din1(p_303_fu_964_p1),
    .dout(p_303_fu_964_p2)
);

demosaic_root_muljbC #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 28 ))
demosaic_root_muljbC_U24(
    .din0(p_362_fu_971_p0),
    .din1(p_362_fu_971_p1),
    .dout(p_362_fu_971_p2)
);

demosaic_root_mulkbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 26 ))
demosaic_root_mulkbM_U25(
    .din0(p_371_fu_978_p0),
    .din1(p_371_fu_978_p1),
    .dout(p_371_fu_978_p2)
);

demosaic_root_mullbW #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 27 ))
demosaic_root_mullbW_U26(
    .din0(p_s_fu_985_p0),
    .din1(p_s_fu_985_p1),
    .dout(p_s_fu_985_p2)
);

demosaic_root_mulmb6 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 21 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 28 ))
demosaic_root_mulmb6_U27(
    .din0(p_8_fu_992_p0),
    .din1(p_8_fu_992_p1),
    .dout(p_8_fu_992_p2)
);

demosaic_root_mulncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 25 ))
demosaic_root_mulncg_U28(
    .din0(p_6_fu_999_p0),
    .din1(p_6_fu_999_p1),
    .dout(p_6_fu_999_p2)
);

demosaic_root_mullbW #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 27 ))
demosaic_root_mullbW_U29(
    .din0(p_19_fu_1006_p0),
    .din1(p_19_fu_1006_p1),
    .dout(p_19_fu_1006_p2)
);

demosaic_root_mulmb6 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 21 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 28 ))
demosaic_root_mulmb6_U30(
    .din0(p_20_fu_1013_p0),
    .din1(p_20_fu_1013_p1),
    .dout(p_20_fu_1013_p2)
);

demosaic_root_mulncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 25 ))
demosaic_root_mulncg_U31(
    .din0(p_21_fu_1020_p0),
    .din1(p_21_fu_1020_p1),
    .dout(p_21_fu_1020_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state21)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((exitcond1_fu_329_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter0 <= 1'b0;
    end else begin
        if (((exitcond_fu_351_p2 == 1'd1) & (1'b0 == ap_block_pp1_stage0_subdone) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
            ap_enable_reg_pp1_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state4)) begin
            ap_enable_reg_pp1_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter10 <= ap_enable_reg_pp1_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter11 <= ap_enable_reg_pp1_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter12 <= ap_enable_reg_pp1_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter13 <= ap_enable_reg_pp1_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter14 <= ap_enable_reg_pp1_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter15 <= ap_enable_reg_pp1_iter14;
        end else if ((1'b1 == ap_CS_fsm_state4)) begin
            ap_enable_reg_pp1_iter15 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp1_exit_iter1_state6)) begin
                ap_enable_reg_pp1_iter2 <= ap_enable_reg_pp1_iter0;
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp1_iter2 <= ap_enable_reg_pp1_iter1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter3 <= ap_enable_reg_pp1_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter4 <= ap_enable_reg_pp1_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter5 <= ap_enable_reg_pp1_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter6 <= ap_enable_reg_pp1_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter7 <= ap_enable_reg_pp1_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter8 <= ap_enable_reg_pp1_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter9 <= ap_enable_reg_pp1_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        p_228_reg_268 <= 20'd0;
    end else if (((exitcond_fu_351_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        p_228_reg_268 <= idx_urem_fu_462_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_op81_read_state6 == 1'b1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        p_329_fu_178 <= p_demosaic_V_bv_V_dout;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        p_329_fu_178 <= p_demosaic_window_1_fu_170;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        p_Val2_7_reg_314 <= p_demosaic_window_v_reg_244;
    end else if (((exitcond_reg_1061_pp1_iter13_reg == 1'd0) & (ap_enable_reg_pp1_iter14 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        p_Val2_7_reg_314 <= p_demosaic_window_0_1_reg_302_pp1_iter13_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        p_demosaic_window_0_1_reg_302 <= p_demosaic_window_0_reg_231;
    end else if (((exitcond_reg_1061_pp1_iter1_reg == 1'd0) & (ap_enable_reg_pp1_iter2 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        p_demosaic_window_0_1_reg_302 <= ret_v_bv_V_1_reg_290;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        p_demosaic_window_1_4_reg_279 <= p_demosaic_window_1_1_reg_206;
    end else if (((exitcond_reg_1061_pp1_iter1_reg == 1'd0) & (ap_enable_reg_pp1_iter2 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        p_demosaic_window_1_4_reg_279 <= p_demosaic_window_1_5_reg_1089;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_prefill_demosaic_reg_195 <= 2'd0;
    end else if (((exitcond1_fu_329_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_prefill_demosaic_reg_195 <= p_prefill_demosaic_1_fu_335_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        p_s0_v_reg_257 <= 20'd0;
    end else if (((exitcond_fu_351_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        p_s0_v_reg_257 <= p_s0_v80_fu_357_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ret_v_bv_V_1_reg_290 <= ret_v_bv_V_reg_218;
    end else if (((exitcond_reg_1061_pp1_iter1_reg == 1'd0) & (ap_enable_reg_pp1_iter2 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        ret_v_bv_V_1_reg_290 <= p_demosaic_window_1_4_reg_279;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        exitcond1_reg_1033 <= exitcond1_fu_329_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        exitcond_reg_1061 <= exitcond_fu_351_p2;
        exitcond_reg_1061_pp1_iter1_reg <= exitcond_reg_1061;
        p_258_reg_1079_pp1_iter1_reg <= p_258_reg_1079;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp1_stage0_11001)) begin
        exitcond_reg_1061_pp1_iter10_reg <= exitcond_reg_1061_pp1_iter9_reg;
        exitcond_reg_1061_pp1_iter11_reg <= exitcond_reg_1061_pp1_iter10_reg;
        exitcond_reg_1061_pp1_iter12_reg <= exitcond_reg_1061_pp1_iter11_reg;
        exitcond_reg_1061_pp1_iter13_reg <= exitcond_reg_1061_pp1_iter12_reg;
        exitcond_reg_1061_pp1_iter2_reg <= exitcond_reg_1061_pp1_iter1_reg;
        exitcond_reg_1061_pp1_iter3_reg <= exitcond_reg_1061_pp1_iter2_reg;
        exitcond_reg_1061_pp1_iter4_reg <= exitcond_reg_1061_pp1_iter3_reg;
        exitcond_reg_1061_pp1_iter5_reg <= exitcond_reg_1061_pp1_iter4_reg;
        exitcond_reg_1061_pp1_iter6_reg <= exitcond_reg_1061_pp1_iter5_reg;
        exitcond_reg_1061_pp1_iter7_reg <= exitcond_reg_1061_pp1_iter6_reg;
        exitcond_reg_1061_pp1_iter8_reg <= exitcond_reg_1061_pp1_iter7_reg;
        exitcond_reg_1061_pp1_iter9_reg <= exitcond_reg_1061_pp1_iter8_reg;
        p_258_reg_1079_pp1_iter10_reg <= p_258_reg_1079_pp1_iter9_reg;
        p_258_reg_1079_pp1_iter11_reg <= p_258_reg_1079_pp1_iter10_reg;
        p_258_reg_1079_pp1_iter12_reg <= p_258_reg_1079_pp1_iter11_reg;
        p_258_reg_1079_pp1_iter13_reg <= p_258_reg_1079_pp1_iter12_reg;
        p_258_reg_1079_pp1_iter14_reg <= p_258_reg_1079_pp1_iter13_reg;
        p_258_reg_1079_pp1_iter2_reg <= p_258_reg_1079_pp1_iter1_reg;
        p_258_reg_1079_pp1_iter3_reg <= p_258_reg_1079_pp1_iter2_reg;
        p_258_reg_1079_pp1_iter4_reg <= p_258_reg_1079_pp1_iter3_reg;
        p_258_reg_1079_pp1_iter5_reg <= p_258_reg_1079_pp1_iter4_reg;
        p_258_reg_1079_pp1_iter6_reg <= p_258_reg_1079_pp1_iter5_reg;
        p_258_reg_1079_pp1_iter7_reg <= p_258_reg_1079_pp1_iter6_reg;
        p_258_reg_1079_pp1_iter8_reg <= p_258_reg_1079_pp1_iter7_reg;
        p_258_reg_1079_pp1_iter9_reg <= p_258_reg_1079_pp1_iter8_reg;
        p_401_reg_1115 <= p_401_fu_937_p2;
        p_demosaic_window_0_1_reg_302_pp1_iter10_reg <= p_demosaic_window_0_1_reg_302_pp1_iter9_reg;
        p_demosaic_window_0_1_reg_302_pp1_iter11_reg <= p_demosaic_window_0_1_reg_302_pp1_iter10_reg;
        p_demosaic_window_0_1_reg_302_pp1_iter12_reg <= p_demosaic_window_0_1_reg_302_pp1_iter11_reg;
        p_demosaic_window_0_1_reg_302_pp1_iter13_reg <= p_demosaic_window_0_1_reg_302_pp1_iter12_reg;
        p_demosaic_window_0_1_reg_302_pp1_iter2_reg <= p_demosaic_window_0_1_reg_302;
        p_demosaic_window_0_1_reg_302_pp1_iter3_reg <= p_demosaic_window_0_1_reg_302_pp1_iter2_reg;
        p_demosaic_window_0_1_reg_302_pp1_iter4_reg <= p_demosaic_window_0_1_reg_302_pp1_iter3_reg;
        p_demosaic_window_0_1_reg_302_pp1_iter5_reg <= p_demosaic_window_0_1_reg_302_pp1_iter4_reg;
        p_demosaic_window_0_1_reg_302_pp1_iter6_reg <= p_demosaic_window_0_1_reg_302_pp1_iter5_reg;
        p_demosaic_window_0_1_reg_302_pp1_iter7_reg <= p_demosaic_window_0_1_reg_302_pp1_iter6_reg;
        p_demosaic_window_0_1_reg_302_pp1_iter8_reg <= p_demosaic_window_0_1_reg_302_pp1_iter7_reg;
        p_demosaic_window_0_1_reg_302_pp1_iter9_reg <= p_demosaic_window_0_1_reg_302_pp1_iter8_reg;
        p_demosaic_window_1_4_reg_279_pp1_iter10_reg <= p_demosaic_window_1_4_reg_279_pp1_iter9_reg;
        p_demosaic_window_1_4_reg_279_pp1_iter11_reg <= p_demosaic_window_1_4_reg_279_pp1_iter10_reg;
        p_demosaic_window_1_4_reg_279_pp1_iter12_reg <= p_demosaic_window_1_4_reg_279_pp1_iter11_reg;
        p_demosaic_window_1_4_reg_279_pp1_iter13_reg <= p_demosaic_window_1_4_reg_279_pp1_iter12_reg;
        p_demosaic_window_1_4_reg_279_pp1_iter2_reg <= p_demosaic_window_1_4_reg_279;
        p_demosaic_window_1_4_reg_279_pp1_iter3_reg <= p_demosaic_window_1_4_reg_279_pp1_iter2_reg;
        p_demosaic_window_1_4_reg_279_pp1_iter4_reg <= p_demosaic_window_1_4_reg_279_pp1_iter3_reg;
        p_demosaic_window_1_4_reg_279_pp1_iter5_reg <= p_demosaic_window_1_4_reg_279_pp1_iter4_reg;
        p_demosaic_window_1_4_reg_279_pp1_iter6_reg <= p_demosaic_window_1_4_reg_279_pp1_iter5_reg;
        p_demosaic_window_1_4_reg_279_pp1_iter7_reg <= p_demosaic_window_1_4_reg_279_pp1_iter6_reg;
        p_demosaic_window_1_4_reg_279_pp1_iter8_reg <= p_demosaic_window_1_4_reg_279_pp1_iter7_reg;
        p_demosaic_window_1_4_reg_279_pp1_iter9_reg <= p_demosaic_window_1_4_reg_279_pp1_iter8_reg;
        p_demosaic_window_1_5_reg_1089_pp1_iter10_reg <= p_demosaic_window_1_5_reg_1089_pp1_iter9_reg;
        p_demosaic_window_1_5_reg_1089_pp1_iter11_reg <= p_demosaic_window_1_5_reg_1089_pp1_iter10_reg;
        p_demosaic_window_1_5_reg_1089_pp1_iter12_reg <= p_demosaic_window_1_5_reg_1089_pp1_iter11_reg;
        p_demosaic_window_1_5_reg_1089_pp1_iter13_reg <= p_demosaic_window_1_5_reg_1089_pp1_iter12_reg;
        p_demosaic_window_1_5_reg_1089_pp1_iter2_reg <= p_demosaic_window_1_5_reg_1089;
        p_demosaic_window_1_5_reg_1089_pp1_iter3_reg <= p_demosaic_window_1_5_reg_1089_pp1_iter2_reg;
        p_demosaic_window_1_5_reg_1089_pp1_iter4_reg <= p_demosaic_window_1_5_reg_1089_pp1_iter3_reg;
        p_demosaic_window_1_5_reg_1089_pp1_iter5_reg <= p_demosaic_window_1_5_reg_1089_pp1_iter4_reg;
        p_demosaic_window_1_5_reg_1089_pp1_iter6_reg <= p_demosaic_window_1_5_reg_1089_pp1_iter5_reg;
        p_demosaic_window_1_5_reg_1089_pp1_iter7_reg <= p_demosaic_window_1_5_reg_1089_pp1_iter6_reg;
        p_demosaic_window_1_5_reg_1089_pp1_iter8_reg <= p_demosaic_window_1_5_reg_1089_pp1_iter7_reg;
        p_demosaic_window_1_5_reg_1089_pp1_iter9_reg <= p_demosaic_window_1_5_reg_1089_pp1_iter8_reg;
        p_demosaic_window_1_6_reg_1095 <= p_329_fu_178;
        p_demosaic_window_1_6_reg_1095_pp1_iter10_reg <= p_demosaic_window_1_6_reg_1095_pp1_iter9_reg;
        p_demosaic_window_1_6_reg_1095_pp1_iter11_reg <= p_demosaic_window_1_6_reg_1095_pp1_iter10_reg;
        p_demosaic_window_1_6_reg_1095_pp1_iter12_reg <= p_demosaic_window_1_6_reg_1095_pp1_iter11_reg;
        p_demosaic_window_1_6_reg_1095_pp1_iter13_reg <= p_demosaic_window_1_6_reg_1095_pp1_iter12_reg;
        p_demosaic_window_1_6_reg_1095_pp1_iter3_reg <= p_demosaic_window_1_6_reg_1095;
        p_demosaic_window_1_6_reg_1095_pp1_iter4_reg <= p_demosaic_window_1_6_reg_1095_pp1_iter3_reg;
        p_demosaic_window_1_6_reg_1095_pp1_iter5_reg <= p_demosaic_window_1_6_reg_1095_pp1_iter4_reg;
        p_demosaic_window_1_6_reg_1095_pp1_iter6_reg <= p_demosaic_window_1_6_reg_1095_pp1_iter5_reg;
        p_demosaic_window_1_6_reg_1095_pp1_iter7_reg <= p_demosaic_window_1_6_reg_1095_pp1_iter6_reg;
        p_demosaic_window_1_6_reg_1095_pp1_iter8_reg <= p_demosaic_window_1_6_reg_1095_pp1_iter7_reg;
        p_demosaic_window_1_6_reg_1095_pp1_iter9_reg <= p_demosaic_window_1_6_reg_1095_pp1_iter8_reg;
        p_odata_window_vs_s_reg_1110 <= p_odata_window_vs_s_fu_929_p3;
        ret_v_bv_V_1_reg_290_pp1_iter10_reg <= ret_v_bv_V_1_reg_290_pp1_iter9_reg;
        ret_v_bv_V_1_reg_290_pp1_iter11_reg <= ret_v_bv_V_1_reg_290_pp1_iter10_reg;
        ret_v_bv_V_1_reg_290_pp1_iter12_reg <= ret_v_bv_V_1_reg_290_pp1_iter11_reg;
        ret_v_bv_V_1_reg_290_pp1_iter13_reg <= ret_v_bv_V_1_reg_290_pp1_iter12_reg;
        ret_v_bv_V_1_reg_290_pp1_iter2_reg <= ret_v_bv_V_1_reg_290;
        ret_v_bv_V_1_reg_290_pp1_iter3_reg <= ret_v_bv_V_1_reg_290_pp1_iter2_reg;
        ret_v_bv_V_1_reg_290_pp1_iter4_reg <= ret_v_bv_V_1_reg_290_pp1_iter3_reg;
        ret_v_bv_V_1_reg_290_pp1_iter5_reg <= ret_v_bv_V_1_reg_290_pp1_iter4_reg;
        ret_v_bv_V_1_reg_290_pp1_iter6_reg <= ret_v_bv_V_1_reg_290_pp1_iter5_reg;
        ret_v_bv_V_1_reg_290_pp1_iter7_reg <= ret_v_bv_V_1_reg_290_pp1_iter6_reg;
        ret_v_bv_V_1_reg_290_pp1_iter8_reg <= ret_v_bv_V_1_reg_290_pp1_iter7_reg;
        ret_v_bv_V_1_reg_290_pp1_iter9_reg <= ret_v_bv_V_1_reg_290_pp1_iter8_reg;
        tmp_23_reg_1100 <= {{p_313_fu_553_p2[19:10]}};
        tmp_25_reg_1105 <= {{p_374_fu_629_p2[19:10]}};
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_fu_351_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        p_221_reg_1070 <= p_221_fu_363_p2;
        p_258_reg_1079 <= p_258_fu_444_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp1_iter14 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        p_Val2_s_fu_174 <= p_odata_window_vs_s_fu_929_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond1_reg_1033 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_demosaic_window_0_reg_231 <= ret_v_bv_V_reg_218;
        p_demosaic_window_1_1_reg_206 <= p_demosaic_window_1_fu_170;
        p_demosaic_window_1_fu_170 <= p_demosaic_V_bv_V_dout;
        p_demosaic_window_v_reg_244 <= p_demosaic_window_0_reg_231;
        ret_v_bv_V_reg_218 <= p_demosaic_window_1_1_reg_206;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        p_demosaic_window_1_5_reg_1089 <= p_329_fu_178;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter1 == 1'b1) & (ap_enable_reg_pp1_iter0 == 1'b0))) begin
        ap_condition_pp1_exit_iter1_state6 = 1'b1;
    end else begin
        ap_condition_pp1_exit_iter1_state6 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter15 == 1'b0) & (ap_enable_reg_pp1_iter1 == 1'b0) & (ap_enable_reg_pp1_iter14 == 1'b0) & (ap_enable_reg_pp1_iter13 == 1'b0) & (ap_enable_reg_pp1_iter12 == 1'b0) & (ap_enable_reg_pp1_iter11 == 1'b0) & (ap_enable_reg_pp1_iter10 == 1'b0) & (ap_enable_reg_pp1_iter9 == 1'b0) & (ap_enable_reg_pp1_iter8 == 1'b0) & (ap_enable_reg_pp1_iter7 == 1'b0) & (ap_enable_reg_pp1_iter6 == 1'b0) & (ap_enable_reg_pp1_iter5 == 1'b0) & (ap_enable_reg_pp1_iter4 == 1'b0) & (ap_enable_reg_pp1_iter3 == 1'b0) & (ap_enable_reg_pp1_iter2 == 1'b0) & (ap_enable_reg_pp1_iter0 == 1'b0))) begin
        ap_idle_pp1 = 1'b1;
    end else begin
        ap_idle_pp1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (exitcond_reg_1061_pp1_iter13_reg == 1'd0) & (ap_enable_reg_pp1_iter14 == 1'b1))) begin
        ap_phi_mux_p_Val2_7_phi_fu_317_p4 = p_demosaic_window_0_1_reg_302_pp1_iter13_reg;
    end else begin
        ap_phi_mux_p_Val2_7_phi_fu_317_p4 = p_Val2_7_reg_314;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        grp_fu_377_ce = 1'b1;
    end else begin
        grp_fu_377_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((p_221_reg_1070 == 1'd1) & (1'b0 == ap_block_pp1_stage0) & (exitcond_reg_1061 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)) | ((exitcond1_reg_1033 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_demosaic_V_bv_V_blk_n = p_demosaic_V_bv_V_empty_n;
    end else begin
        p_demosaic_V_bv_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_predicate_op81_read_state6 == 1'b1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)) | ((exitcond1_reg_1033 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        p_demosaic_V_bv_V_read = 1'b1;
    end else begin
        p_demosaic_V_bv_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((p_401_reg_1115 == 1'd1) & (1'b0 == ap_block_pp1_stage0) & (p_258_reg_1079_pp1_iter14_reg == 1'd0) & (ap_enable_reg_pp1_iter15 == 1'b1))) begin
        p_odata_V_bv_V_blk_n = p_odata_V_bv_V_full_n;
    end else begin
        p_odata_V_bv_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_predicate_op187_write_state20 == 1'b1) & (ap_enable_reg_pp1_iter15 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        p_odata_V_bv_V_write = 1'b1;
    end else begin
        p_odata_V_bv_V_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_pp1_stage0;
        end
        ap_ST_fsm_pp1_stage0 : begin
            if ((~((ap_enable_reg_pp1_iter2 == 1'b0) & (1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter0 == 1'b0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)) & ~((ap_enable_reg_pp1_iter14 == 1'b0) & (1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter15 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else if ((((ap_enable_reg_pp1_iter14 == 1'b0) & (1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter15 == 1'b1)) | ((ap_enable_reg_pp1_iter2 == 1'b0) & (1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter0 == 1'b0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)))) begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp1_stage0 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((exitcond1_reg_1033 == 1'd0) & (p_demosaic_V_bv_V_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((exitcond1_reg_1033 == 1'd0) & (p_demosaic_V_bv_V_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_pp1_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp1_stage0_01001 = (((p_odata_V_bv_V_full_n == 1'b0) & (ap_predicate_op187_write_state20 == 1'b1) & (ap_enable_reg_pp1_iter15 == 1'b1)) | ((p_demosaic_V_bv_V_empty_n == 1'b0) & (ap_predicate_op81_read_state6 == 1'b1) & (ap_enable_reg_pp1_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp1_stage0_11001 = (((p_odata_V_bv_V_full_n == 1'b0) & (ap_predicate_op187_write_state20 == 1'b1) & (ap_enable_reg_pp1_iter15 == 1'b1)) | ((p_demosaic_V_bv_V_empty_n == 1'b0) & (ap_predicate_op81_read_state6 == 1'b1) & (ap_enable_reg_pp1_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp1_stage0_subdone = (((p_odata_V_bv_V_full_n == 1'b0) & (ap_predicate_op187_write_state20 == 1'b1) & (ap_enable_reg_pp1_iter15 == 1'b1)) | ((p_demosaic_V_bv_V_empty_n == 1'b0) & (ap_predicate_op81_read_state6 == 1'b1) & (ap_enable_reg_pp1_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state10_pp1_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp1_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp1_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp1_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp1_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp1_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp1_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp1_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp1_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp1_stage0_iter14 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state20_pp1_stage0_iter15 = ((p_odata_V_bv_V_full_n == 1'b0) & (ap_predicate_op187_write_state20 == 1'b1));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = ((exitcond1_reg_1033 == 1'd0) & (p_demosaic_V_bv_V_empty_n == 1'b0));
end

assign ap_block_state5_pp1_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state6_pp1_stage0_iter1 = ((p_demosaic_V_bv_V_empty_n == 1'b0) & (ap_predicate_op81_read_state6 == 1'b1));
end

assign ap_block_state7_pp1_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp1_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp1_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_pp1 = (ap_idle_pp1 ^ 1'b1);

always @ (*) begin
    ap_predicate_op187_write_state20 = ((p_401_reg_1115 == 1'd1) & (p_258_reg_1079_pp1_iter14_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op81_read_state6 = ((p_221_reg_1070 == 1'd1) & (exitcond_reg_1061 == 1'd0));
end

assign exitcond1_fu_329_p2 = ((p_prefill_demosaic_reg_195 == 2'd3) ? 1'b1 : 1'b0);

assign exitcond_fu_351_p2 = ((p_s0_v_reg_257 == 20'd921600) ? 1'b1 : 1'b0);

assign grp_fu_377_p1 = 11'd3;

assign idx_urem_fu_462_p3 = ((tmp_27_fu_456_p2[0:0] === 1'b1) ? next_urem_fu_450_p2 : 20'd0);

assign mul_fu_948_p0 = 24'd2731;

assign mul_fu_948_p1 = mul_fu_948_p10;

assign mul_fu_948_p10 = tmp_14_fu_373_p1;

assign next_urem_fu_450_p2 = (p_228_reg_268 + 20'd1);

assign p_19_fu_1006_p0 = 27'd313344;

assign p_19_fu_1006_p1 = p_19_fu_1006_p10;

assign p_19_fu_1006_p10 = p_demosaic_window_1_4_reg_279_pp1_iter13_reg;

assign p_20_fu_1013_p0 = 28'd614400;

assign p_20_fu_1013_p1 = p_20_fu_1013_p10;

assign p_20_fu_1013_p10 = p_demosaic_window_1_5_reg_1089_pp1_iter13_reg;

assign p_21_fu_1020_p0 = 25'd119808;

assign p_21_fu_1020_p1 = p_21_fu_1020_p10;

assign p_21_fu_1020_p10 = p_demosaic_window_1_6_reg_1095_pp1_iter13_reg;

assign p_221_fu_363_p2 = ((p_s0_v_reg_257 < 20'd921597) ? 1'b1 : 1'b0);

assign p_248_fu_652_p3 = grp_fu_377_p2[32'd1];

assign p_249_cast1_fu_396_p1 = tmp_6_fu_387_p4;

assign p_251_fu_430_p2 = (tmp_2_fu_424_p2 + tmp_13_fu_369_p1);

assign p_258_fu_444_p2 = (tmp_22_fu_436_p3 ^ tmp_21_fu_400_p3);

assign p_260_2_fu_665_p2 = (p_260_fu_660_p2 & p_248_fu_652_p3);

assign p_260_fu_660_p2 = (p_258_reg_1079_pp1_iter13_reg ^ 1'd1);

assign p_269_cast_fu_684_p1 = tmp_9_fu_675_p4;

assign p_276_cast_fu_692_p4 = {{p_8_fu_992_p2[27:10]}};

assign p_284_cast_fu_714_p1 = tmp_s_fu_705_p4;

assign p_285_fu_724_p2 = (tmp1_fu_718_p2 + p_269_cast_fu_684_p1);

assign p_289_fu_746_p3 = ((tmp_i_fu_730_p2[0:0] === 1'b1) ? tmp_fu_736_p4 : 8'd255);

assign p_292_fu_481_p3 = {{ap_phi_mux_p_Val2_7_phi_fu_317_p4}, {10'd0}};

assign p_295_fu_957_p0 = 27'd134217556;

assign p_295_fu_957_p1 = p_295_fu_957_p10;

assign p_295_fu_957_p10 = p_292_fu_481_p3;

assign p_300_fu_506_p3 = {{p_demosaic_window_0_1_reg_302_pp1_iter12_reg}, {10'd0}};

assign p_301_cast_fu_514_p1 = p_300_fu_506_p3;

assign p_303_fu_964_p0 = 28'd268435117;

assign p_303_fu_964_p1 = p_301_cast_fu_514_p1;

assign p_308_cast_cast_fu_539_p1 = p_308_fu_531_p3;

assign p_308_fu_531_p3 = {{ret_v_bv_V_1_reg_290_pp1_iter12_reg}, {9'd0}};

assign p_313_fu_553_p2 = ($signed(tmp2_cast_fu_549_p1) + $signed(p_cast6_fu_527_p1));

assign p_315_fu_757_p2 = ($signed(11'd128) + $signed(tmp_14_cast_fu_754_p1));

assign p_316_fu_769_p3 = ((tmp_i1_fu_763_p2[0:0] === 1'b1) ? p_315_fu_757_p2 : 11'd255);

assign p_318_fu_787_p3 = ((tmp_i2_fu_777_p2[0:0] === 1'b1) ? tmp_24_fu_783_p1 : 8'd0);

assign p_328_cast_fu_808_p1 = tmp_10_fu_799_p4;

assign p_336_cast_fu_815_p4 = {{p_20_fu_1013_p2[27:10]}};

assign p_345_cast_fu_836_p1 = tmp_11_fu_827_p4;

assign p_346_fu_846_p2 = (tmp3_fu_840_p2 + p_328_cast_fu_808_p1);

assign p_350_fu_868_p3 = ((tmp_i3_fu_852_p2[0:0] === 1'b1) ? tmp_5_fu_858_p4 : 8'd255);

assign p_353_cast_cast_fu_577_p1 = p_353_fu_569_p3;

assign p_353_fu_569_p3 = {{ap_phi_mux_p_Val2_7_phi_fu_317_p4}, {9'd0}};

assign p_362_fu_971_p0 = 28'd268435028;

assign p_362_fu_971_p1 = p_301_cast_fu_514_p1;

assign p_368_fu_594_p3 = {{ret_v_bv_V_1_reg_290_pp1_iter12_reg}, {10'd0}};

assign p_371_fu_978_p0 = 26'd67108781;

assign p_371_fu_978_p1 = p_371_fu_978_p10;

assign p_371_fu_978_p10 = p_368_fu_594_p3;

assign p_374_fu_629_p2 = ($signed(tmp4_cast_fu_625_p1) + $signed(p_cast5_fu_590_p1));

assign p_376_fu_879_p2 = ($signed(11'd128) + $signed(tmp_20_cast_fu_876_p1));

assign p_377_fu_891_p3 = ((tmp_i4_fu_885_p2[0:0] === 1'b1) ? p_376_fu_879_p2 : 11'd255);

assign p_379_fu_909_p3 = ((tmp_i5_fu_899_p2[0:0] === 1'b1) ? tmp_26_fu_905_p1 : 8'd0);

assign p_401_fu_937_p2 = ((tmp_19_fu_648_p1 == 3'd2) ? 1'b1 : 1'b0);

assign p_6_fu_999_p0 = 25'd119808;

assign p_6_fu_999_p1 = p_6_fu_999_p10;

assign p_6_fu_999_p10 = ret_v_bv_V_1_reg_290_pp1_iter13_reg;

assign p_8_fu_992_p0 = 28'd614400;

assign p_8_fu_992_p1 = p_8_fu_992_p10;

assign p_8_fu_992_p10 = p_demosaic_window_0_1_reg_302_pp1_iter13_reg;

assign p_Result_s_fu_917_p5 = {{{{p_379_fu_909_p3}, {p_350_fu_868_p3}}, {p_318_fu_787_p3}}, {p_289_fu_746_p3}};

assign p_cast5_fu_590_p1 = $signed(tmp_12_fu_581_p4);

assign p_cast6_fu_527_p1 = $signed(tmp_8_fu_518_p4);

assign p_cast7_fu_502_p1 = $signed(tmp_1_fu_493_p4);

assign p_cast_fu_615_p1 = $signed(tmp_15_fu_606_p4);

assign p_odata_V_bv_V_din = p_odata_window_vs_s_reg_1110;

assign p_odata_window_vs_s_fu_929_p3 = ((p_260_2_fu_665_p2[0:0] === 1'b1) ? p_Result_s_fu_917_p5 : p_Val2_s_fu_174);

assign p_prefill_demosaic_1_fu_335_p2 = (p_prefill_demosaic_reg_195 + 2'd1);

assign p_s0_v80_fu_357_p2 = (p_s0_v_reg_257 + 20'd1);

assign p_s_fu_985_p0 = 27'd313344;

assign p_s_fu_985_p1 = p_s_fu_985_p10;

assign p_s_fu_985_p10 = p_Val2_7_reg_314;

assign p_shl_fu_416_p3 = {{tmp_7_fu_407_p4}, {2'd0}};

assign tmp1_fu_718_p2 = (p_276_cast_fu_692_p4 + p_284_cast_fu_714_p1);

assign tmp2_cast_fu_549_p1 = $signed(tmp2_fu_543_p2);

assign tmp2_fu_543_p2 = ($signed(p_cast7_fu_502_p1) + $signed(p_308_cast_cast_fu_539_p1));

assign tmp3_fu_840_p2 = (p_336_cast_fu_815_p4 + p_345_cast_fu_836_p1);

assign tmp4_cast_fu_625_p1 = $signed(tmp4_fu_619_p2);

assign tmp4_fu_619_p2 = ($signed(p_353_cast_cast_fu_577_p1) + $signed(p_cast_fu_615_p1));

assign tmp_10_fu_799_p4 = {{p_19_fu_1006_p2[26:10]}};

assign tmp_11_fu_827_p4 = {{p_21_fu_1020_p2[24:10]}};

assign tmp_12_fu_581_p4 = {{p_362_fu_971_p2[27:10]}};

assign tmp_13_fu_369_p1 = p_228_reg_268[11:0];

assign tmp_14_cast_fu_754_p1 = $signed(tmp_23_reg_1100);

assign tmp_14_fu_373_p1 = p_228_reg_268[10:0];

assign tmp_15_fu_606_p4 = {{p_371_fu_978_p2[25:10]}};

assign tmp_19_fu_648_p1 = grp_fu_377_p2[2:0];

assign tmp_1_fu_493_p4 = {{p_295_fu_957_p2[26:10]}};

assign tmp_20_cast_fu_876_p1 = $signed(tmp_25_reg_1105);

assign tmp_21_fu_400_p3 = mul_fu_948_p2[32'd13];

assign tmp_22_fu_436_p3 = p_251_fu_430_p2[32'd11];

assign tmp_24_fu_783_p1 = p_316_fu_769_p3[7:0];

assign tmp_26_fu_905_p1 = p_377_fu_891_p3[7:0];

assign tmp_27_fu_456_p2 = ((next_urem_fu_450_p2 < 20'd1920) ? 1'b1 : 1'b0);

assign tmp_2_fu_424_p2 = (p_249_cast1_fu_396_p1 - p_shl_fu_416_p3);

assign tmp_5_fu_858_p4 = {{p_346_fu_846_p2[17:10]}};

assign tmp_6_fu_387_p4 = {{mul_fu_948_p2[23:13]}};

assign tmp_7_fu_407_p4 = {{mul_fu_948_p2[22:13]}};

assign tmp_8_fu_518_p4 = {{p_303_fu_964_p2[27:10]}};

assign tmp_9_fu_675_p4 = {{p_s_fu_985_p2[26:10]}};

assign tmp_fu_736_p4 = {{p_285_fu_724_p2[17:10]}};

assign tmp_i1_fu_763_p2 = (($signed(p_315_fu_757_p2) < $signed(11'd255)) ? 1'b1 : 1'b0);

assign tmp_i2_fu_777_p2 = (($signed(p_316_fu_769_p3) > $signed(11'd0)) ? 1'b1 : 1'b0);

assign tmp_i3_fu_852_p2 = ((p_346_fu_846_p2 < 18'd261120) ? 1'b1 : 1'b0);

assign tmp_i4_fu_885_p2 = (($signed(p_376_fu_879_p2) < $signed(11'd255)) ? 1'b1 : 1'b0);

assign tmp_i5_fu_899_p2 = (($signed(p_377_fu_891_p3) > $signed(11'd0)) ? 1'b1 : 1'b0);

assign tmp_i_fu_730_p2 = ((p_285_fu_724_p2 < 18'd261120) ? 1'b1 : 1'b0);

assign tmp_s_fu_705_p4 = {{p_6_fu_999_p2[24:10]}};

endmodule //odata
